### ISSUE TITLE
Error Help ---> "Exception raised in the backend: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by Archmeister94** [Kapiainen/Lauhdutin#100]
So I was having a bit of a paddy with my game playing up it then crashed, so I just held down the power button, after turning it on I got this "Exception raised in the backend: Expecting value: line 1 column 1 (car 0)".  Don't know why it's happening, I restarted my computer and refreshed the skin but nothing.

Rainmeter: 4.1.0 beta r2858 64x
Lauhdutin version: 2.7.1
Python version: 3.6.2 / I used the installer I think
Windows: 10 64x Enterprise 2016 LTSB 
Error: Exception raised in the backend: Expecting value: line 1 column 1 (char 0)

**Comment by BanCrash** [comment]
Could you check if your games.json (placed inside the @Resources folder in the skin folder) is correct?

Also you can change in skin settings the python path from pythonw to python, and check what warning is appearing.

**Comment by Archmeister94** [comment]
Did it, games.json was empty, I deleted and refreshed the skin and everything worked perfectly, thank you :D

**Comment by BanCrash** [comment]
Perfect! Glad to help ;)
