### ISSUE TITLE
[Question] Display Game Title instead of platform

### ISSUE THREAD

**Issue by durwi** [Kapiainen/Lauhdutin#106]
## Is there any way to replace the platform string with the game's name?
Not an issue, but a question. Hope this is the correct place to post.
I know the skin/script reads the game cause it's displaying when there's no banner.
I have decreased the tile size for the images but now some titles are hard to read.

**Comment by BanCrash** [comment]
Right now is not possible, however if you know something of lua shouldn't be difficult to make that.

You have to edit some parts of Update function that starts on line 1155 of GUI.lua (in master branch) to do that.

**Comment by Kapiainen** [comment]
The game name is shown on the slot overlay in version 3.0.0.
