### ISSUE TITLE
Community profile not being downloaded

### ISSUE THREAD

**Issue by Tene21** [Kapiainen/Lauhdutin#110]
The skin is not downloading my community profile from the steam servers. 

The skin itself is hanging on `Detecting Steam games` and upon turning on the log, I can see that it's hanging on `Attempting to download file:    http://steamcommunity.com/profiles/[id number here]/games/?tab=all&xml=1    communityProfile.txt    OnCommunityProfileDownloaded    OnCommunityProfileDownloadFailed`

It was working normally until a short while ago, but this has persisted across multiple restarts and even after downloading beta 5

**Comment by Tene21** [comment]
Five minutes after the hang, it has finally updated, but has lost track of all playtime. I can see in the log that an error did occur while downloading, `Download failed (res=0x800C000B, COM=0x00000000): http://steamcommunity.com/profiles/[id number here]/games/?tab=all&xml=1 (Lauhdutin\Main.ini - [Downloader])`, if that's any help in troubleshooting.

**Comment by Kapiainen** [comment]
How long has this been going on?

I just tested completely removing my copy of `games.json` and all backups to force everything to reset to what can be gathered from the various platforms. No issues with accessing my Steam community profile nor with acquiring the hours played from that profile.

You removed your ID from the log message you posted so I cannot test if the page loads, but have you done that via a browser? If the issue goes away, then it might have been an issue e.g. with your connection to the content delivery network that Valve use for their Steam services.

I'm not sure how the skin would have lost track of the hours played stat short of the names of games being changed. If you had an existing copy of `games.json` with the hours played stats intact, then the skin would always override whatever values it got from e.g. the Steam community profile with the values stored in that file provided that the values in `games.json` were greater than those gathered from the community profile.
