### ISSUE TITLE
Left click search in installed games

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#112]
Hello, on the last beta (6), I see that searching with left click made a search on installed games, instead of all games.

In the readme I see that:

> Left-clicking the button searches all games.

So I guess this is a bug and should search on all games, not only installed.

**Comment by Kapiainen** [comment]
That would be an error in the documentation. It should specify `all installed games`.

**Comment by BanCrash** [comment]
Ah, okay! I see that you already fixed it, so I close this. Thanks for the answer!
