### ISSUE TITLE
Error: 96: attempt to index global 'bannerURLs' (a nil value)

### ISSUE THREAD

**Issue by villicush** [Kapiainen/Lauhdutin#116]
## Short description of the issue

I'm getting an error message about bannerURLs

## Lauhdutin version

3.0.0 beta 9

## Rainmeter version

4.1 Final Release

## Python version

3.6, used the installer.

## Windows version

Windows 10 Home (Version 1709)

## Error messages

Displayed on the skin: 

Error: 96: attempt to index global 'bannerURLs' (a nil value)

![errormsg](https://user-images.githubusercontent.com/33588623/39610042-21f0592a-4f13-11e8-96fc-2ac62e53b03b.PNG)

## Steps to reproduce the issue

I ran the settings, put in my steam, battle.net, and gog information (including sqlite), then I ran Main.ini and that message showed up.

## Python stack traceback

sorry, don't know what to put here :P

**Comment by Kapiainen** [comment]
The new release (3.0.0 beta 10) is out now and should fix this issue. Thanks for notifying me of the issue.
