### ISSUE TITLE
Update banner of games

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#117]
Hello again! I have a new suggestion. I was thinking of have the option "update banner" in Game.ini. There are games that changes its banner on certain circunstances (for example, when releasing new content, or exiting Early Access program), and could be useful have the option to update their banner without manually removing the existing banner. 

Beside, I want to know if you changed your mind about "completed" option for games, or will be added in a future release.

**Comment by Kapiainen** [comment]
I'll take it into consideration for version 3.1.0. The solution would have to be platform-dependent. For Steam games you can generate the URL to the banner based on a base/template URL and the game's AppID, but for e.g. GOG Galaxy you would either have to re-acquire the URL from the database or always store it in `games.json`. I'd rather avoid putting a bunch of extra information, which is going to be irrelevant most of the time, into `games.json`.

At the moment you can click on the banner in `Game.ini` to open the image in the default program for that file format and at least with Windows Photo Viewer you can delete the banner without going to the folder containing the banner. You would then have to refresh the skin to download the new banner.

At the moment I think that the `Completed` status of a game should be handled by the user via the existing tag system.

**Comment by BanCrash** [comment]
Perfect, thanks you!!

**Comment by Kapiainen** [comment]
This has now been implemented in the [branch for version 3.1.0](https://github.com/Kapiainen/Lauhdutin/tree/development-v3-1). The option is available for Steam and GOG Galaxy games.

**Comment by BanCrash** [comment]
I just tried with a steam game and works perfect! Thanks again!
