### ISSUE TITLE
Skin not showing hours properly

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#118]
Hello! I found two little issues related to hours showed. I'm using last beta.

- When a game only has one hour of play skin is showing "1 hours" instead "1 hour":

![image](https://user-images.githubusercontent.com/11770760/39968211-ee7c59ae-56c9-11e8-9b47-e43a6bd3a2f0.png)

- When a game has more than "x.5" hours skin is showing "x+1 hours" instead "x hours". For example, in NBA 2K17 I have "17.7" in games.json, and the skin is showing "18 hours" instead "17 hours". But maybe it's a feature and not an issue?

![image](https://user-images.githubusercontent.com/11770760/39968268-c245449e-56ca-11e8-82fa-09f3a93c10a0.png)
![image](https://user-images.githubusercontent.com/11770760/39968270-c7d76658-56ca-11e8-955e-f1d0653f0863.png)

**Comment by Kapiainen** [comment]
> When a game has more than "x.5" hours skin is showing "x+1 hours" instead "x hours". For example, in NBA 2K17 I have "17.7" in games.json, and the skin is showing "18 hours" instead "17 hours". But maybe it's a feature and not an issue?

That is intentional. The number of hours played is always rounded up or down.

> When a game only has one hour of play skin is showing "1 hours" instead "1 hour":

That should probably be handled with a separate translation string for the case where the value is rounded up or down to 1. For the English translation one could get away with using `X hour(s)`, but that would not work for all languages (e.g. Swedish has the pattern `1 timme` and `2+ timmar`).

**Comment by Kapiainen** [comment]
I just pushed a commit that adds a translation string for the case where a game has been played for approximately 1 hour (i.e. the value is rounded up or down to 1).

**Comment by BanCrash** [comment]
> That is intentional. The number of hours played is always rounded up or down.
Well then!
> I just pushed a commit that adds a translation string for the case where a game has been played for approximately 1 hour (i.e. the value is rounded up or down to 1).
Perfect, thanks you!!
