### ISSUE TITLE
Can't load games

### ISSUE THREAD

**Issue by ablacklama** [Kapiainen/Lauhdutin#119]
## Short description of the issue
"No Games to show" after adding steam path. It detected my steam name, but not any games.

## Error messages
no log errors

**Comment by Kapiainen** [comment]
Do you happen to have the `Parse community profile` option enabled? If yes, then have you set your Steam community profile to be public in your Steam profile settings?

**Comment by ablacklama** [comment]
I did have that enabled and I have my profile set to public

**Comment by Kapiainen** [comment]
Have you updated your Steam profile settings since the changes that Valve implemented to the setting defaults about a month ago?

**Comment by hollowuniverse** [comment]
Hi just wanted to add i've been having the same issue and have tried all of the above. The only version i've been able to get to detect my games is 2.7.1

**Comment by Kapiainen** [comment]
@hollowuniverse Which platforms' games are you trying to detect?

If Steam is among them, then:
- What kind of setup do you have in terms of where games are installed (e.g. all in the main Steam folder or some/all in a Steam library on another partition)? 
- Are there `appmanifest_X.acf` files (replace `X` with a game's AppID) in the `Steam\steamapps` folder(s)?
- Did you enable parsing of the community profile? If so, then did you make sure to make your community profile public?
- Could you open `\Lauhdutin\@Resources\games.json` in a text editor (e.g. Notepad) and check if there are **any** games in there at all?

**Comment by Revadike** [comment]
Try (re)moving this folder: `\documents\Rainmeter\Skins\Lauhdutin\@Resources\cache`
This will reset all settings.
