### ISSUE TITLE
Parse steam once per day

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#121]
Hello! I was thinking of having the option to parse Steam profile once per day, so if you refresh the skin on the same day and you have this option enabled will skip the parsering until next day. I'm thinking of this because my rainmeter crash many times lately, and I like to avoid have to enable and disable every day parsering to avoid those unnecesary parsering.

The way I think this could be done is to read modification time of games.json files, and if the day is today avoid parsering.

I also think that could be added the option to set how often this happens instead only once per day, but this will complicate so many the implementation I guess.

**Comment by Kapiainen** [comment]
One would presumably also need to have some way of manually forcing the community profile to be parsed the next time that the skin is refreshed (e.g. if you buy a game and want it to show up in the skin without waiting until the next scheduled time).

**Comment by BanCrash** [comment]
> One would presumably also need to have some way of manually forcing the community profile to be parsed the next time that the skin is refreshed (e.g. if you buy a game and want it to show up in the skin without waiting until the next day).

Right, could were an option for that in "Custom skin actions" as "rebuild skin" option that were on 2.x version.

> This could actually be applied to all platforms and it would probably reduce the start-up time for the skin when loading it repeatedly during e.g. a day. Run the (currently) usual detection of games, parsing of the community profile, etc. once per user-defined period or whenever triggered manually by the user.

You're right, without that I think the skin would be started in a flash!

> I'll add this to the todo list and give it some more thought.

Perfect, thanks you again!

**Comment by Kapiainen** [comment]
This has now been implemented in the [branch for version 3.1.0](https://github.com/Kapiainen/Lauhdutin/tree/development-v3-1). There is an option to set how often games should be detected: never, once per day, or always (the current behavior in version 3.0.0).

**Comment by BanCrash** [comment]
Perfect, thanks you!!

I just tried and with "never" selected is started veeeery quick. Nice job!
