### ISSUE TITLE
Invalid path when trying to launch a shortcut

### ISSUE THREAD

**Issue by Issue12** [Kapiainen/Lauhdutin#122]
## Short description of the issue
Invalid path overlay only when trying to launch a shortcut through steam & lauhdutin
## Lauhdutin version
2.7.1
## Rainmeter version
4.1.0 beta r2944 64bit

## Python version
2.4

## Windows version
1809
## Error messages
None. Unless you count the invalid path overlay

## Steps to reproduce the issue
Create a shortcut from the .bat file attached, add the shortcut as a non steam game and try to launch through lauhdutin. 
[FortniteLaunch.zip](https://github.com/Kapiainen/Lauhdutin/files/2035113/FortniteLaunch.zip)

**Comment by sassanix** [comment]
Try the latest version, it works for me.
