### ISSUE TITLE
Epic launcher game is still running

### ISSUE THREAD

**Issue by sassanix** [Kapiainen/Lauhdutin#128]
## Short description of the issue
After creating a shortcut to epic launcher once it's loaded and closed out of the system it thinks that it's still running even though it's completely closed and not running in the background. 

So the Lauhdutin launcher will not re-open as it's hidden because of the fact it thinks a game is running. 

## Lauhdutin version
3.0.1

## Rainmeter version
4.2.0 beta r3029 64-bit (Feb  8 2018)

## Windows version
Windows 10 Pro 64-bit (build 16299)

## Error messages

DBUG (23:11:52.963) : Monitoring process    EpicGamesLauncher.exe
DBUG (23:11:53.301) : Animations.resetSlots
DBUG (23:12:03.965) : Updating game process status
DBUG (23:12:03.975) : Game is still running
DBUG (23:12:05.548) : Updating game process status
DBUG (23:12:05.556) : Game is still running
DBUG (23:12:07.240) : Updating game process status
DBUG (23:12:07.249) : Game is still running
DBUG (23:12:08.827) : Updating game process status
DBUG (23:12:08.836) : Game is still running
DBUG (23:12:10.388) : Updating game process status
DBUG (23:12:10.397) : Game is still running
DBUG (23:12:11.963) : Updating game process status
DBUG (23:12:11.972) : Game is still running
DBUG (23:12:13.552) : Updating game process status
DBUG (23:12:13.560) : Game is still running
DBUG (23:12:15.114) : Updating game process status
DBUG (23:12:15.123) : Game is still running
DBUG (23:12:16.699) : Updating game process status
DBUG (23:12:16.708) : Game is still running
DBUG (23:12:18.266) : Updating game process status
DBUG (23:12:18.274) : Game is still running
DBUG (23:12:19.837) : Updating game process status
DBUG (23:12:19.846) : Game is still running
DBUG (23:12:21.424) : Updating game process status
DBUG (23:12:21.433) : Game is still running
DBUG (23:12:22.993) : Updating game process status
DBUG (23:12:23.002) : Game is still running
DBUG (23:12:24.574) : Updating game process status
DBUG (23:12:24.582) : Game is still running
DBUG (23:12:26.140) : Updating game process status
DBUG (23:12:26.149) : Game is still running
DBUG (23:12:27.717) : Updating game process status
DBUG (23:12:27.726) : Game is still running
DBUG (23:12:29.299) : Updating game process status
DBUG (23:12:29.308) : Game is still running
DBUG (23:12:30.865) : Updating game process status
DBUG (23:12:30.874) : Game is still running
DBUG (23:12:32.453) : Updating game process status
DBUG (23:12:32.462) : Game is still running
DBUG (23:12:34.014) : Updating game process status
DBUG (23:12:34.023) : Game is still running
DBUG (23:12:35.587) : Updating game process status
DBUG (23:12:35.596) : Game is still running
DBUG (23:12:37.178) : Updating game process status
DBUG (23:12:37.187) : Game is still running
DBUG (23:12:38.740) : Updating game process status
DBUG (23:12:38.749) : Game is still running
DBUG (23:12:40.324) : Updating game process status
DBUG (23:12:40.333) : Game is still running

And continues onward 

## Steps to reproduce the issue
Creating a shortcut to the epic launcher and running a game and closing the game and also closing the launcher but it still thinks the game is running.

**Comment by BanCrash** [comment]
Just for adding, could your check in taskmanager if epic launcher still has a process? I'm saying this because I had the same problem and the issue was that even closing the launcher the process is still open.

**Comment by sassanix** [comment]
So I did that, I added a new process in there for Fornite launcher. Yet after I close Fortnite, after I close the Epic launcher that's when the Lauhdutin launcher comes back up. But it's a hit or miss, there's a lot of Fortnite processes in the background, maybe it's freaking out? It opens up 3 of them

**Comment by BanCrash** [comment]
One of them is for anti-cheats, other for the launcher and other for the game itself. I'm using "FortniteClient-Win64-Shipping.exe" (game itself process), but I only play the game 2 times, so I can't assure you it works properly all the times.

**Comment by sassanix** [comment]
So I should add FortniteClient-Win64-Shipping.exe to the process portion as Kapiainen suggested?

**Comment by BanCrash** [comment]
That's correct.

**Comment by sassanix** [comment]
I think it got fixed, now that I did that. Thanks again :)
