### ISSUE TITLE
Remove games when filtering

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#129]
Hello! When I see the new "lacks tags" filter, I think of going far: Having the hability of have that for every filter.

For example, when general filtering, if you right-click on "platform/Steam" will show all games that aren't from Steam. And when you are filtering on the actual list, if you right-click on "platform/Steam" will remove from the current filtered list games that are from Steam, leaving all games that aren't from that platform.

**Comment by Kapiainen** [comment]
Sounds like a good idea, but I'm wondering about the implementation. Maybe there should be an option to invert all of the listed filters? So e.g. a list of filters:
> Has never been played
> Is on platform
> etc.

becomes:

> Has been played
> Is not on platform
> etc.

I'm not quite sure if the default stance of the filters should be changed (e.g. `Has never been played` would be replaced by `Has been played` as the default, but `Is on platform` would remain as it is) and then use the invert filters option. Or maybe the filters should default to whatever is most likely to be the most commonly used case (e.g. I think that people are more likely to look for games that they have not played as opposed to games that they have played, if that is the only criterion). Another example is the `Has tag` filter, which I think would be used much more than the inverse and thus should remain the default for quick access. Perhaps the invert filters option should be at the top of the list of filters as well to make it quicker to access?

Maybe there should also be an option to invert the current filter stack? So if you've applied a few filters and want the games that are excluded by the filters, then you could just choose this option and the skin will display the games that were excluded by the filter stack.

What do you think?

**Comment by BanCrash** [comment]
> Maybe there should be an option to invert all of the listed filters at the top-level? 

Sounds well enough, with that you can see what will you get, making easier to the people to understand what will happen.

> I'm not quite sure if the default stance of the filters should be changed (e.g. Has never been played would be replaced by Has been played as the default, but Is on platform would remain as it is) and then use the invert filters option. Or maybe the filters should default to whatever is most likely to be the most commonly used case (e.g. I think that people are more likely to look for games that they have not played as opposed to games that they have played, if that is the only criterion). Another example is the Has tag filter, which I think would be used much more than the inverse and thus should remain the default for quick access.

I think the same, default state could be the most commonly used case to try to avoid unnecessary clicks (IMO "Has tags", "Has never been played", "Is not installed", "is on platform" and "Random game"). By the way, just a funny idea I get, maybe Random game could remove a random game when inversed? :joy:

> Perhaps the invert filters option should be at the top of the list of filters as well to make it quicker to access?

I think that's the best way, yes. It would be more used than "clear filters" or "cancel", so seems logical placed it on first place. Other option I think is doing that when you right click on "filter" title, and go back to "normal" filter when you left click. With that you can invert filters wherever you are, but I'm not very certain about if it's a good idea.

> Maybe there should also be an option to invert the current filter stack? So if you've applied a few filters and want the games that are excluded by the filters, then you could just choose this option and the skin will display the games that were excluded by the filter stack.

Sounds useful indeed!

**Comment by Kapiainen** [comment]
I just pushed a commit that implements inverted filters, but I still haven't implemented the ability to invert the entire filter stack. I do appreciate the joke regarding `Random game`, but I labeled them properly to prevent the frustration the suggested behavior might cause if the label didn't change along with the behavior.

**Comment by BanCrash** [comment]
I just tested and seems to work like a charm! Thanks!
