### ISSUE TITLE
Latest GOG Galaxy update breaks Lauhdutin

### ISSUE THREAD

**Issue by sassanix** [Kapiainen/Lauhdutin#130]
## Short description of the issue
Games won't load after GOG got updated, error message comes up 

## Lauhdutin version
3.0.1

## Rainmeter version
4.2.0 beta r3029 64-bit (Feb 8 2018)

## Windows version
Windows 10 Pro 64-bit (build 16299)

## Error messages
![image](https://user-images.githubusercontent.com/39465071/40690477-ab52e164-637d-11e8-9311-1264d2411dfc.png)

DBUG (20:18:08.147) : Initializing skin
DBUG (20:18:08.154) : Loading translation file
DBUG (20:18:08.164) : Initializing
DBUG (20:18:08.896) : Detecting games
DBUG (20:18:08.909) : Num platforms:    4
DBUG (20:18:08.915) : Registering platform processes
DBUG (20:18:08.920) : - 2 = Steam.exe
DBUG (20:18:08.926) : - 3 = Battle.net.exe
DBUG (20:18:08.932) : - 4 = GalaxyClient.exe
DBUG (20:18:08.938) :  Windows shortcut = true
DBUG (20:18:08.944) :  Steam = true
DBUG (20:18:08.950) :  Blizzard Battle.net = true
ERRO (20:18:08.956) Lauhdutin.-.3.0.1\Main.ini: Error: init.lua:10: The path to GOG Galaxy's ProgramData directory is not valid.

## Steps to reproduce the issue
Loading my computer and or refreshing rainmeter

**Comment by BanCrash** [comment]
Do you have any game installed on GOG Galaxy? Seems like last update removes index.db from my ProgramData GOG folder, but I don't have any game installed so I don't know if they delete index.db if you don't have any game installed or they will handle library with ownership.db from now...

**Comment by Kapiainen** [comment]
This should be fixed in 3.0.2, which was just released.

**Comment by sassanix** [comment]
Awesome! Is it possible to update without having to go through all the settings?

**Comment by Kapiainen** [comment]
All of your games and settings are stored in `\Lauhdutin\@Resources\games.json` and `\Lauhdutin\@Resources\settings.json`, respectively. Neither of those are included in releases so you should be able to just overwrite the files of the old version with the files of the new version. The only thing you'll need to do is either not overwrite `\Lauhdutin\dist\@Resources\main\slots\init.inc` or go to the skin's settings, right-click somewhere on the settings skin, and click on `Rebuild main slots`. Alternatively you can adjust any settings related to the slots (orientation, width, height, etc.), save, and close to force the main skin to be rebuilt according to your settings.

**Comment by sassanix** [comment]
I copied the @resource folder onto the new one and I get this error again

NOTE (18:56:22.737) Lauhdutin.-.3.0.3\Main.ini: Refreshing skin
DBUG (18:56:22.762) : Initializing skin
DBUG (18:56:22.770) : Loading translation file
DBUG (18:56:22.781) : Initializing
DBUG (18:56:25.016) : Detecting games
DBUG (18:56:25.030) : Num platforms:    4
DBUG (18:56:25.037) : Registering platform processes
DBUG (18:56:25.044) : - 2 = Steam.exe
DBUG (18:56:25.051) : - 3 = Battle.net.exe
DBUG (18:56:25.057) : - 4 = GalaxyClient.exe
DBUG (18:56:25.064) :  Windows shortcut = true
DBUG (18:56:25.071) :  Steam = true
DBUG (18:56:25.077) :  Blizzard Battle.net = true
ERRO (18:56:25.084) Lauhdutin.-.3.0.3\Main.ini: Error: init.lua:10: The path to GOG Galaxy's ProgramData directory is not valid.

**Comment by Kapiainen** [comment]
You can't copy the entire `@Resource` folder. You can copy `@Resources\cache` for the banners, `@Resources\games.json` for data relevant to your games (hours played, tags, etc.), and `@Resources\settings.json` for your skin settings from an older version.

**Comment by sassanix** [comment]
That worked beautifully, had to take my shortcuts as well and then did the rebuild main slot and all good :)
