### ISSUE TITLE
About GOG

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#135]
Hello! I see on the to-do list that you are planning to add suport for gog wishlist. Could be added the option to have uninstalled games now? With the new profile there is an option to show them, and there is a privacy option to set them to "all visitors".

![image](https://user-images.githubusercontent.com/11770760/40971477-09b6e2ec-68be-11e8-8593-55ebf4b6ffbb.png)

I assume that if wishlist could be parsed maybe games page could be parsed too, but maybe I'm wrong.

The web to see games on a public profile is: https://www.gog.com/u/INSERT_PROFILE_HERE/games . If the profile is privated, a warning will be showed instead games:

![image](https://user-images.githubusercontent.com/11770760/40971614-878efa38-68be-11e8-8074-64a750c6c076.png)

**Comment by Kapiainen** [comment]
The source of the wishlist page includes all of the necessary information whereas the games page does not. It looks like the games page uses JavaScript to get the information rather than including them in the page source.

**Comment by BanCrash** [comment]
Ouch, okay! Then will wait until a way to accomplish that appears then. Thanks for the answer.

**Comment by Kapiainen** [comment]
I did a quick test with PhantomJS, which is a headless browser, and was able to successfully get the necessary information.  Using PhantomJS would add an optional requirement, but at least installing it is as simple as placing one executable in the skin's `@Resources` folder. Chrome and Firefox have headless modes so I'm going to see if I can use them to get the necessary information. It might be possible to use a browser that is already installed and have PhantomJS as a backup.

**Comment by BanCrash** [comment]
Glad to read that! Hope it will work so we can have all possible games without many complications!

**Comment by Kapiainen** [comment]
I'm having issues with Chrome's headless mode and I get the impression that both Chrome's and Firefox's headless modes are quite limited unless one uses drivers, which require additional, large dependencies. PhantomJS seems to be the way to go due to the simplicity of installing and using it.

**Comment by BanCrash** [comment]
Well, at least sounds easy for the final user (and not easy at all for the programmer).

**Comment by Kapiainen** [comment]
I just pushed commits to implement downloading and parsing GOG profiles to find games associated with an account. I still need to update the readme and have a look at extracting the hours played from the profile. If you want to test it out, then you'll need to grab [PhantomJS](http://phantomjs.org/download.html) and place it in the `@Resources` folder.

**Comment by BanCrash** [comment]
Perfect! Testing this matter I found another unrelated issue. 
![image](https://user-images.githubusercontent.com/11770760/41054716-73e64c14-69bf-11e8-89cf-90b71ccd8291.png)
I said it's unrelated because I try [this commit](https://github.com/Kapiainen/Lauhdutin/tree/cc60e873b4c9069e841d23c784a219f37730de17) from 5 days ago for example and have the same issue. However trying last release doesn't happen.

Steps to replicate: Delete games.json, backups and settings.json. Open settings.ini, enable for example Windows Shortcut Platform and then Save and close. 

About this matter, I tested it and seems to work great! Thanks, nice job!

**Comment by BanCrash** [comment]
Perfect. Thanks!

**Comment by Kapiainen** [comment]
I pushed commits that implemented parsing the hours played from the profile.

**Comment by BanCrash** [comment]
I don't know why I thought this is completed. I'll let this open until next release.

I just tested and works great. Thanks!
