### ISSUE TITLE
Issue when removing a game

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#138]
Hello! I found a little issue on both 3.0.3 and last development commit. When removing a game the game it's removed and the game that are on their right side is "removed" too, but it's only from vision. After a refresh (with detecting games disabled, so it's not a reaquisition) will be showed again:

Before removing Plants vs Zombies GW2:
![image](https://user-images.githubusercontent.com/11770760/41102179-8c016188-6a66-11e8-94e0-a3ead18258a9.png)

After removing it, The Walking dead a new frontier disappears:
![image](https://user-images.githubusercontent.com/11770760/41102215-a1f7eafc-6a66-11e8-8129-55ffcf6d0cb6.png)

After refresh skin after that appears again:
![image](https://user-images.githubusercontent.com/11770760/41102265-bd6d06be-6a66-11e8-8104-28827b610a2b.png)

> Rainmeter 4.2.0 beta r3074 64-bit (Jun  1 2018) - Spanish (3082)
> Windows 10 Pro 1803 64-bit (build 17134) - Spanish (3082)

**Comment by Kapiainen** [comment]
I think I found the cause and another potential bug. I've pushed a commit that should fix them both.

**Comment by BanCrash** [comment]
Tried again and doesn't happens anymore. Thanks!
