### ISSUE TITLE
Games.inc Non-steam games aren't showing up

### ISSUE THREAD

**Issue by Torchie1455** [Kapiainen/Lauhdutin#14]
![image](https://cloud.githubusercontent.com/assets/25116447/21953602/94be1358-da01-11e6-8f39-0c3be277fe69.png)

![image](https://cloud.githubusercontent.com/assets/25116447/21953605/a0b196ee-da01-11e6-8090-1c8420e086ae.png)

My custom games aren't seeming to appear...any advice on what I'm doing wrong?

**Comment by Xarishark** [comment]
What windows theme is that?

**Comment by draema** [comment]
I had the same issue but then found this: 
[https://www.reddit.com/r/Rainmeter/comments/5hr4bi/help_with_using_nonsteam_games_in_lauhdutin/](url)

Delete any blank lines in the file and refresh skin.

**Comment by Kapiainen** [comment]
I won't be providing support for versions other than the latest version. If anyone is experiencing this issue with a version of Lauhdutin older than the latest one, then update to the latest version. If there are still issues, then feel free to open a new issue.
