### ISSUE TITLE
Twitch games support [WIP]

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#145]
- [ ] Modify Readme
- [ ] Modify changelog
- [x] Batch file to dump databases with sqlite3
- [ ] Modify Game / Game.moon
- [x] Modify Main / Platforms / Init.moon
- [x] Create Main / Platforms / Twitch.moon
- - [x] Dump databases function
- - [x] Parse Install info function
- - - [x] Scenario when no games are installed right now should be accounted
- - [x] Parse products info function
- - [x] Parse fuel info function
- - [x] All platform common functions
- - [ ] Add tests if possible
- [ ] ¿Modify Main / Slots / Overlay_slots.moon?
- [ ] Modify Main / init.moon
- [ ] Modify Settings / init.moon
- [ ] Create Settings / Pages / twitch.moon
- - [ ] Option for enable or disable platform
- - [ ] Bangs options
- - [ ] AppData folder selection, with standard option as default
- - [ ] ProgramData folder selection, with standard option as default
- [x] Modify Shared / Enums.moon
- [ ] ¿Modify Shared / Library.moon?
- [ ] Modify Shared / Settings.moon
- [ ] Modify Translation / English.txt
- [ ] Modify build_release.py

DONE:

- [x] Investigate all files that should be modified to add full support
- - [x] Filter Folder
- - [x] Game Folder
- - [x] Lib Folder
- - [x] Main Folder
- - [x] NewGame Folder
- - [x] Search Folder
- - [x] Session Folder
- - [x] Settings Folder
- - [x] Shared Folder
- - [x] Sort Folder
- - [x] Translations
- - [x] Root Folder (.gitattributes, etc)

ORIGINAL COMMENT:

Hello! I made an investigation and I think games from Twitch store could be fully supported.

- I found on AppData\Roaming\Twitch\Games\Sql a sql database file named GameProductInfo.sqlite that has all the necessary info about all owned games (only have owned games, not all games like GOG) in a table named "DbSet": ProductIdStr (which is the folder name of the game), ProductTitle (Game name) and various tables about covers. The main cover (named ProductIconUrl) is vertically ([example](http://ecx.images-amazon.com/images/I/91Pr0vynV4L.png)), so I suggest to add Background2 field as cover ([example](https://images-na.ssl-images-amazon.com/images/I/91eojAJfhSL.png
)).

![image](https://user-images.githubusercontent.com/11770760/42531898-828c1ba0-8485-11e8-80d0-6cc744b9b105.png)
![image](https://user-images.githubusercontent.com/11770760/42531936-a205765c-8485-11e8-8a23-f999dc80acaa.png)
![image](https://user-images.githubusercontent.com/11770760/42531945-a874edc4-8485-11e8-9776-340c8d454e9e.png)

- When you choose to install a game, you only can choose in what unit you want to install it, but you can't choose the folder itself.

![image](https://user-images.githubusercontent.com/11770760/42530714-2a14dc76-8482-11e8-8a2d-26702edf18a7.png)

However, I think it's better to let the user choose games installation folder/s as on blizzard Battle.net, to avoid issues that could arise.

- When you install a game, a folder with ProductIdStr is created on installation folder:

![image](https://user-images.githubusercontent.com/11770760/42531067-491479aa-8483-11e8-90af-031bd59c3cf2.png)
![image](https://user-images.githubusercontent.com/11770760/42531158-84d4ec04-8483-11e8-9887-9cde848bac1b.png)
![image](https://user-images.githubusercontent.com/11770760/42531175-955d0dcc-8483-11e8-803b-645dc9f186e4.png)
![image](https://user-images.githubusercontent.com/11770760/42531189-a42b5cfa-8483-11e8-8d4f-e7f3f0ce7c2e.png)

So is easily to know which owned games are installed.

- And to launch a game is easy as: "twitch://fuel-launch/ProductIdStr of the game".

![image](https://user-images.githubusercontent.com/11770760/42531642-c1fd96ca-8484-11e8-84cd-801ac262e7dd.png)
![image](https://user-images.githubusercontent.com/11770760/42531645-c7fb7772-8484-11e8-88b9-bfc4a0b870fc.png)

![image](https://user-images.githubusercontent.com/11770760/42531709-f8b12326-8484-11e8-9e8c-e37ac40f13da.png)
![image](https://user-images.githubusercontent.com/11770760/42531740-0be4533c-8485-11e8-8e67-e6284dc88fde.png)

And if you use that command with an uninstalled game, you will get this popup:
![image](https://user-images.githubusercontent.com/11770760/42531802-3c39fef6-8485-11e8-98ed-83387d509361.png)

Translation: "Game is not installed. Would you like to install it now?"

In resume, sqlite3 could get ProductIdStr, ProductTitle, and Background2 from DbSet on C:\Users\User\AppData\Roaming\Twitch\Games\Sql\GameProductInfo.sqlite, then will check folders placed on games installation folder to see which games are installed, and then games would be launched or installed with twitch://fuel-launch/ProductIdStr.

EDIT; After more research, I found another sql file (C:\ProgramData\Twitch\Games\Sql\GameInstallInfo.sqlite) that has only installed games. Has also previous installed games, but with field "Installed" with 0 instead 1. So will be better than check folders to see if they're installed.

![image](https://user-images.githubusercontent.com/11770760/42638472-05aafdf8-85ee-11e8-8557-4401e8c99771.png)

**Comment by Kapiainen** [comment]
I'm probably not going to implement and maintain support for it for a few reasons:
1) Several games available via the service require Steam anyway.
2) I have not been able to find a free game that I could use to generate the database and test it.
3) Amazon's presence in my country is limited, which means that some regional restrictions apply, and I don't have an account.

Feel free to implement it yourself, but I'm reluctant to do it since I don't use it myself and would be unable to properly maintain support for it.

**Comment by BanCrash** [comment]
I understand why you're reluctant. I will try to implement to see if I can make it work.

For now I will let this closed until I know if I'm capable to do so.

**Comment by BanCrash** [comment]
I'm working on this and I have a doubt about the actual code. I'm using gog galaxy code as basis, and I found that on function OnDumpedDBs [there is a call to: cachePath = STATE.PLATFORM_QUEUE[1]\getCachePath(). ](https://github.com/Kapiainen/Lauhdutin/blob/development-v3/src/main/init.moon#L849)

I see the gog galaxy platform file, but [in the actual development3 version](https://github.com/Kapiainen/Lauhdutin/blob/development-v3/src/main/platforms/gog_galaxy/init.moon#L56) there isn't any function named "getCachePath()". However, [in the master version yes there is](https://github.com/Kapiainen/Lauhdutin/blob/master/src/main/platforms/gog_galaxy/init.moon#L47). That function was moved to other part? I can't find it.

**Comment by Kapiainen** [comment]
The definition for that method can be found [here](https://github.com/Kapiainen/Lauhdutin/blob/development-v3/src/main/platforms/platform.moon#L34) in the `Platform` class that all platforms extend.

**Comment by BanCrash** [comment]
Ah, perfect then, thanks you!

**Comment by BanCrash** [comment]
I have to polish things and fix stuff, but right now uninstalled games are detected and have their banners dowloaded:

![image](https://user-images.githubusercontent.com/11770760/42733509-986a4716-8832-11e8-9a48-853f324cb618.png)

I see on your TODO list that you are making a refactor, so I will wait until that is done to make this PR for adapt the code to that refactor.
