### ISSUE TITLE
Edit notes not working

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#146]
Hello! On 3.1.0 Beta 1, when try to edit notes on Game.ini, nothing happens. I enable the logger to see if something happens, but nothing appears.

I'm using the recent 4.2 Rainmeter version, for if there is any issue with that version.

> 4.2.0 r3111 64-bit (Jul  8 2018) - Spanish (3082)
> Windows 10 Pro 1803 64-bit (build 17134) - Spanish (3082)

By the way, in this version is added the option to [disable or enable mouse actions](https://docs.rainmeter.net/manual/bangs/#MouseAction) whenever you want. I think this could be added to disable slots when are unused (when are less games than slots).

**Comment by Kapiainen** [comment]
It is working fine for me, but then again I am still using Rainmeter 4.0.0 r2746. Have you tried doing the same thing in an earlier version of Lauhdutin after you updated to Rainmeter 4.2?

It is nice that skins can now toggle mouse actions instead of having to implement that behavior with Lua. However, this skin already uses Lua scripts so I don't see the need to use the feature. At least not at the moment.

**Comment by BanCrash** [comment]
> It is working fine for me, but then again I am still using Rainmeter 4.0.0 r2746. Have you tried doing the same thing in an earlier version of Lauhdutin after you updated to Rainmeter 4.2?

Yes, but after more testings I found the problem. I named the folder "Lauhdutin 3.1.0" as always. But if I rename it to "Lauhdutin" works perfect. So would be an issue with spaces in the name.

> It is nice that skins can now toggle mouse actions instead of having to implement that behavior with Lua. However, this skin already uses Lua scripts so I don't see the need to use the feature. At least not at the moment.

Sure. I just commented it thinking of those AnimationsResetSlots that appears on the logger when I hover on an empty slot while testing this matter and to avoid the hand of the mouse cursor that suggest you can click. Minor details.

**Comment by Kapiainen** [comment]
Okay, I'll look into the issue.

**Comment by BanCrash** [comment]
Perfect, thanks!

**Comment by Kapiainen** [comment]
The latest beta version should fix the issue both for editing notes and bangs. I switched over to using relative paths instead of absolute. I'm not quite sure why Rainmeter split the absolute paths at every space despite the paths being surrounded by quotes.

**Comment by BanCrash** [comment]
Perfect, thanks! Weird indeed.
