### ISSUE TITLE
Can't turn the skin vertically.

### ISSUE THREAD

**Issue by Issue12** [Kapiainen/Lauhdutin#147]
## Short description of the issue

Skin will not turn vertical. Always horizontal despite settings skin and .ini file saying otherwise

## Rainmeter version

4.2 Final.

## Windows version

Version	10.0.17134 Build 17134

## Error messages

No errors

## Steps to reproduce the issue

Download latest lauhdutin version. Unpack into skins folder. Open w/ rainmeter. Try to change orientation.

**Comment by Kapiainen** [comment]
You need to adjust the numbers of rows and columns. The checkbox you are referring to affects how games move when you scroll. You can try it out with e.g. a 2x3 grid and toggling the setting.
