### ISSUE TITLE
Show last added games?

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#149]
Hello! I was thinking that when new games are detected, could be a skin that shows what are those detected games.

I'm thinking of something like this:

![image](https://user-images.githubusercontent.com/11770760/43600130-13a452cc-968a-11e8-9b5c-6ebaffad5ac0.png)

The way I think is to create a table with new games when those are detected to avoid write addition dates on games.json, so this will show added games just in the actual "cycle" of the skin. When the skin is closed or refreshed, they're gone. This will avoid increase the size of the games.json file.

The other option is to do exactly that, write the addition dates on games.json, and then you're be able to order games also with their addition date. However, like I said, this will increase the size of games.json file.

**Comment by Kapiainen** [comment]
One could probably just add a temporary table to `games.json` with each new game's gameID, which are only valid during the session that the IDs were generated anyway. That table would then be removed (or replaced with a new one if more games are detected) the next time that the skin is loaded. Were you thinking of a scrollable list of games? What do you think about e.g. an overlay (name, platform, installed or uninstalled, etc.) when you hover the mouse over a game? Perhaps the number of new games should be shown somewhere? The menu should probably be optional.

**Comment by BanCrash** [comment]
After your questions I think that this could have two parts:

The menu as showed, just with the images to have a initial perspective of what is added (if you enable that), with the option to do scroll to show all added games. But nothing except that.

And then add a new filter that will show all last added games (if any), the number (as you said), and when selecting that filter you will have the option to show their overlay, play, etc.

So if you have it enabled on the startup you'll have a visual information of what been added, but in any case you will be able to filter the last games if exits, interact with them, etc.
