### ISSUE TITLE
Loading time

### ISSUE THREAD

**Issue by Revadike** [Kapiainen/Lauhdutin#155]
My rainmeter would take minutes to start up and was unresponsive until it was loaded. I quickly identified it was due to your Lauhdutin skin. 
I have a huge steam library and this is likely the cause of the issue. All I want is to show my installed steam games (only 79) sorted by last played. Can't this be optimized?
I tried to remove my sharedconfig and localconfig files from steam, but that didn't have any affect. Perhaps it's better to get last played data from the steam web api?
Anyway, any tips on how to speed up this loading would be appreciated!

**Comment by Revadike** [comment]
I also noticed my `\documents\Rainmeter\Skins\Lauhdutin\@Resources\cache\steam` folder is 1 GB, 14,719 items... It seems unnecessary to download all those, if I just wanna see my installed games.

**Comment by BanCrash** [comment]
Hello, to only add your installed games of steam instead all you have to uncheck "Parse Steam profile" on Settings -> Steam. But this would not remove your actual database. Check if without parsing your profile the skin loads faster, and if not I suggest you to remove your actual database (\documents\Rainmeter\Skins\Lauhdutin\@Resources\games.json and all backups if any) and then reloading skin, so it only will add installed games,

**Comment by Revadike** [comment]
Thanks, that makes sense. I didn't know it would read backups if I removed games.json

**Comment by Revadike** [comment]
That fixed the issue! Now it load in mere seconds!

**Comment by BanCrash** [comment]
Glad to read that ;)
