### ISSUE TITLE
After save and exit i get this error

### ISSUE THREAD

**Issue by Xarishark** [Kapiainen/Lauhdutin#16]
![image](https://cloud.githubusercontent.com/assets/21146743/22353901/6603c074-e42b-11e6-9e4f-9516101c2005.png)

**Comment by Kavex** [comment]
Go into Lauhdutin\@Resources\ and delete settings.json file. This will allow you to fill out the information

**Comment by Xarishark** [comment]
still having the error i have the latest python and rainmeter.

**Comment by Xarishark** [comment]
![image](https://cloud.githubusercontent.com/assets/21146743/22357885/d69716a2-e443-11e6-894e-a10190e065dc.png)

**Comment by Xarishark** [comment]
versions are on the right.

**Comment by Kavex** [comment]
From looking at the code I believe that error comes from an incorrect steam path. I'm not sure if the GUI is filling out or reading the .json correctly. What does the  `"steam_path":""` say in the settings.json under  `Lauhdutin\@Resources\` ?

Mine doesn't seem to fill out any settings in the settings.json nor does it the browse button work. I've manually edit the Frontend Settings.lua to auto fill this information for me but it still refuses to get pass Processing. 

Any input on this Kapiainen?

**Comment by Xarishark** [comment]
"steam_path":"C:\/Program Files (x86)\/Steam"

**Comment by Kavex** [comment]
You forgot to put code markdown so is it this? `"steam_path":"C:\/Program Files (x86)\/Steam"`

**Comment by Xarishark** [comment]
oh shit
yes thats how it is

**Comment by Kapiainen** [comment]
Could you modify `Python="pythonw"` to `Python="python"` in the *Main.ini* file and try loading that config? The line in question is under the *Variables* section. The command prompt will then be visible when the Python script is executed and hopefully help to narrow down the source of the problem. The scripts should print out some stuff including a stack traceback, if an exception was caught.

**Comment by Kavex** [comment]
It's throwing an ImportError in BannerDownloader.py 

No module named request

**Comment by Kapiainen** [comment]
That is odd. *urllib.request* is part of the standard library and has been for a long time (at least since 3.3.0 according to available documentation). Could you verify by opening up the Python interpreter and trying to import that module (`import urllib.request`)?

**Comment by Kavex** [comment]
Yeah it was added awhile ago 

It imports without throwing an error in the interpreter

**Comment by Kavex** [comment]
I think it wants to run Python 2.7 since I have both installed

I changed import from `urllib.request ` to  `urllib ` and it runs just fine. You might need to throw in a check.

**Comment by Xarishark** [comment]
So what do i need to do?

**Comment by Kavex** [comment]
@Xarishark Go into `Lauhdutin\@Resources\Backend\` and open `BannerDownloader.py` 

Change `import os, urllib.request, time` to `import os, urllib, time`

**Comment by Xarishark** [comment]
stuck at processing now

**Comment by Xarishark** [comment]
no network activity indicating that it downloads anything

**Comment by Kavex** [comment]
@Xarishark Please modify `Python="pythonw"` to `Python="python"` in the Main.ini

**Comment by Xarishark** [comment]
done and still stuck at processing 
![image](https://cloud.githubusercontent.com/assets/21146743/22361249/90123c6c-e460-11e6-8922-9f94f5789375.png)

**Comment by Kapiainen** [comment]
Could you post a screenshot of the Python script's output to the console?

**Comment by Kavex** [comment]
@Xarishark a terminal window should have popped up

What did it say? and you are refreshing the skin right?

**Comment by Xarishark** [comment]
Yes im refreshing there is no terminal open tho. It appears and disappears instantly

**Comment by Kavex** [comment]
@Xarishark Delete the Lauhdutin folder and re-add a fresh one then modify `Python="pythonw"` to `Python="python"` in the Main.ini and run the setup.

**Comment by Xarishark** [comment]
![image](https://cloud.githubusercontent.com/assets/21146743/22361516/2ccd0ed6-e463-11e6-8dc8-f53e0f937852.png)

**Comment by Kapiainen** [comment]
Could you open *\Lauhdutin\@Resources\Backend\Steam.py* and replace line 33

`with open(a_path) as f:`

with this

`with open(a_path, encoding="utf-8") as f:`

**Comment by Xarishark** [comment]
![image](https://cloud.githubusercontent.com/assets/21146743/22361738/490ca4f6-e465-11e6-8646-bb26a1a3f8ce.png)

**Comment by Xarishark** [comment]
how do i hade the terminal now?

**Comment by Xarishark** [comment]
also anyway to make the orientation horizontal pls?

**Comment by Kavex** [comment]
@Xarishark Change back to `Python="pythonw` in Main.ini and this should make the terminal disappear.

**Comment by Xarishark** [comment]
what about the horizontality ?

**Comment by Kavex** [comment]
Kapiainen has to answer that one because I have no clue about the new version

**Comment by Xarishark** [comment]
ty!

**Comment by Kapiainen** [comment]
Horizontal orientation is not supported at the moment, but it is on the list of stuff to add in the next version.

**Comment by Kavex** [comment]
@Kapiainen 

You might want to write an if statement for BannerDownloader.py in case someone has both version of python installed. For some reason BannerDownloader.py wanted to run 2.7 even tho the path was set to 3.6. 
``` 
import sys

if sys.version_info[0] == 3:
    import os, urllib.request, time
else:
    import os, urllib, time
```

Or at least a Frontend warning if python 2.7 is running

Might save you a future headache, food for thought.

**Comment by Kapiainen** [comment]
@Kavex I'd rather avoid the hassle of supporting both Python 2.x and 3.x. I support both major versions in a few other projects because I have to, but I'd rather not have that headache in this project. I'll be adding some checks, extra print statements, pass more info about exceptions straight to the skin, etc. for the next version. Among those things will straight up be a warning that, as you suggested, the system is trying to run the Python scripts with an unsupported version.

**Comment by Kavex** [comment]
@Kapiainen 

I totally understand and the more information on the exceptions will be nice :) Good work so far

I'll have to fix the problem with it running 2.7 which isn't hard but not everyone is so computer literate as us even tho Python happens to be on the low end of the totem pole for me as for languages I know.

Cheers :3

**Comment by Kapiainen** [comment]
@Kavex Thanks. And thank you for the issue template and helping out with this issue report. I'm adding a Python path setting to the settings GUI to make it easier to adjust and also adding it to the *settings.json* file so that the value can be retained when updating from one version of Lauhdutin 2.x.x to the next.

**Comment by Kavex** [comment]
@Kapiainen You're very welcome, I find the templates very useful for my stuff. You should edit it more so people are required to present more information then just "It's broken!!!" when creating an issue ticket. XD

Also I'd suggest using the Wiki too :)

**Comment by Kapiainen** [comment]
@Xarishark Version 2.1.0 adds support for a horizontal layout (a toggle can be found in the settings menu).
