### ISSUE TITLE
Trying to add Blizzard games

### ISSUE THREAD

**Issue by Wiggin38** [Kapiainen/Lauhdutin#2]
Hi,

I hate to be a bother but I am trying to figure out how to add Blizzard/Origin games. They don't have an appid so I am a little lost. Is the appid used for the banner ? 

I have added the below to Games.inc 
The appid is the same as what I named the custom banner in the banners folder.

"1"
{
    "path"    "E:\Blizzard Games\Heroes of the Storm\Heroes of the Storm.exe"
    "appid"   "14704491514860404736"
    "name"    "Heroes of the storm"
    "tags"
    {
        "0"   "MOBA"
    }
}

I would very much appreciate some direction.

**Comment by Kapiainen** [comment]
The AppID should be the same as the name of your banner (without the extension). If you used the *Add game* function of the skin and left the *Steam AppID* section empty, then the skin will set the name of the game as the AppID. If the AppID is a number, then the skin assumes that it is a Steam AppID and attempts to download the banner. However if there already is a banner with a name that matches an AppID, then that local copy is used and no attempts are made to download a banner from Steam. AppIDs are also used to launch games, which have been purchased via Steam, by using Steam's browser protocol. Non-Steam games need to have the *path* key-value pair.

Your entry looks correct, assuming that you have a banner called *14704491514860404736* and its extension is either *.jpg* or *.png*. If the banner has another extension that is supported by Rainmeter, then you can add the extension to this line (70) in [*Lauhdutin.lua*](https://github.com/Kapiainen/Lauhdutin/blob/master/Lauhdutin/Lauhdutin.lua#L70).

**Comment by Wiggin38** [comment]
Hey, 

Thanks for the quick response. I got it working finally. I was having issues with using the Add game feature but was able to add them manually and using the shortcut on the desktop method. 

I have added the below to Games.inc

"1"
{
        "LastPlayed"        "1430247509"
		"appid"	    "14704491514860404736"
        "name"      "Heroes of the Storm"
        "path"      "steam://rungameid/14704491514860404736"
}
"2"
{
		"LastPlayed"        "1430247509"
		"appid"		"17765925958428131328"		
		"name"		"Star Craft II"	
		"path"		"steam://rungameid/17765925958428131328"
	}		

My last issue is that if I launch a non-steam game via my steam library (ie Starcraft II) the game starts but the game does not go to the top of "recently played". If I launch through your launcher it does. My question is, is there anyway to get it to go to the top of the list no matter where I launch the game from or will it only work when I launch through your launcher ? 

Thanks again   
- Wiggin

**Comment by Kapiainen** [comment]
Games, which have been added to you Steam library as non-Steam game shortcuts, should be picked up automatically by the skin, but you would have to provide banners for them. Steam writes info about the non-Steam game shortcuts to *\Steam\userdata\USERDATAID\config\shortcuts.vdf*, but it only writes the name, the path to the executable, whether or not the shortcut is set to be hidden, and any tags/categories the shortcut has been placed in. So at the moment you would have to launch the games via Lauhdutin in order to have them update the timestamp for when they were last played.
