### ISSUE TITLE
How do you scroll the ticker?

### ISSUE THREAD

**Issue by tenzion** [Kapiainen/Lauhdutin#20]
Maybe it's a stupid question, but how does the ticker work? Is it manual scroll or should it work with mouse over left/right or top/bottom?

**Comment by Kapiainen** [comment]
Use the mouse scroll wheel.

**Comment by tenzion** [comment]
No. Does not work. Logitech MX Master...
I can hover over the ticker, but nothing happens when I either scroll the wheel or press the wheel and scroll...

**Comment by tenzion** [comment]
What can I do to test it? Where does the problem reside? With the mouse, the driver, or the software? What mouse do you use yourself?

**Comment by Kapiainen** [comment]
You could paste the following into a .ini file and load it in Rainmeter. It should print messages in the log and on the skin when you use the scroll wheel, left mouse button, right mouse button, and when the cursor enters/leaves the skin. This will hopefully help to figure out if Rainmeter is having an issue detecting your scroll wheel. I'm using a Logitech M705.

```
[Metadata]
Name=Mouse test

[Rainmeter]
Update=10000
Blur=1

[Variables]
Status=Waiting...

[Box]
Meter=Image
X=0
Y=0
W=256
H=256
SolidColor=64,64,64,255
LeftMouseDownAction=[!Log "Left mouse down"][!SetVariable "Status" "Left mouse down" ][!Update]
LeftMouseUpAction=[!Log "Left mouse up"][!SetVariable "Status" "Left mouse up" ][!Update]
LeftMouseDoubleClickAction=[!Log "Left mouse double click"][!SetVariable "Status" "Left mouse double click" ][!Update]
RightMouseDownAction=[!Log "Right mouse down"][!SetVariable "Status" "Right mouse down" ][!Update]
RightMouseUpAction=[!Log "Right mouse up"][!SetVariable "Status" "Right mouse up" ][!Update]
RightMouseDoubleClickAction=[!Log "Right mouse double click"][!SetVariable "Status" "Right mouse double click" ][!Update]
MouseOverAction=[!Log "Mouse over"][!SetVariable "Status" "Mouse over"][!Update]
MouseLeaveAction=[!Log "Mouse leave"][!SetVariable "Status" "Mouse leave"][!Update]
MouseScrollUpAction=[!Log "Mouse scroll up"][!SetVariable "Status" "Mouse scroll up"][!Update]
MouseScrollDownAction=[!Log "Mouse scroll down"][!SetVariable "Status" "Mouse scroll down"][!Update]
MouseScrollLeftAction=[!Log "Mouse scroll left"][!SetVariable "Status" "Mouse scroll left"][!Update]
MouseScrollRightAction=[!Log "Mouse scroll right"][!SetVariable "Status" "Mouse scroll right"][!Update]
MiddleMouseDownAction=[!Log "Middle mouse down"][!SetVariable "Status" "Middle mouse down"][!Update]
MiddleMouseUpAction=[!Log "Middle mouse up"][!SetVariable "Status" "Middle mouse up"][!Update]
MiddleMouseDoubleClickAction=[!Log "Middle mouse double click"][!SetVariable "Status" "Middle mouse double click"][!Update]

[Message]
Meter=String
X=128
Y=128
W=248
H=248
FontSize=15
FontColor=255,255,255,255
StringAlign=CenterCenter
Text=#Status#
DynamicVariables=1
```

**Comment by tenzion** [comment]
Rainmeter.ini I guess?
It seems with v2.2.0 beta 1 all my shortcuts/banners for non-steam games do not work anymore. All the shortcuts/banners are still there though.

**Comment by Kapiainen** [comment]
You could just create a new folder in `\Rainmeter\Skins\`, create a new .ini file, and paste the config above into it.

Any errors in the log?

**Comment by tenzion** [comment]
Ok. Works.
No errors in the log when using your provided .ini file. All actions I take with the mouse with the .ini file corresponds with the output.

**Comment by tenzion** [comment]
I managed to get it working. It seems when using a slot count that exceeds the height or width of your screen, you of course cannot scroll... But decreasing the slot count so that it is small enough to fit on your screen, you can scroll within it... Sorry for not figuring that out sooner...

**Comment by Kapiainen** [comment]
I'll have to look into that and try to reproduce the issue.

**Comment by Kapiainen** [comment]
Did you just increase the slot count until the skin extended outside of the monitor either widthwise or heightwise? I did that and did not encounter any issues.
