### ISSUE TITLE
Since v2.3.0 not working, see image

### ISSUE THREAD

**Issue by tenzion** [Kapiainen/Lauhdutin#26]
Since v2.3.0, the plugin is not working anymore.
![image](https://cloud.githubusercontent.com/assets/1419242/23157153/35f66032-f81a-11e6-9e79-1db2775c1875.png)

not working with v2.4.0 alpha 4 either.

python v3.6
windows 10
rainmeter 4.0.0.2746

**Comment by Kapiainen** [comment]
Could you set the Python path setting to `python` so that the terminal shows up? I'll need to see the stack traceback so that I can see which script is failing and on which line.

**Comment by Kapiainen** [comment]
The latest alpha (5) contains a fix that hopefully applies to this issue.

**Comment by alszeliga** [comment]
The latest download (2.4.0 Alpha6) fixed the problem for me and I can see my steam and non steam games. However, another issue, non-steam games do not display a header image, even if I set a custom one. See the attached image:

![image](https://cloud.githubusercontent.com/assets/25847227/23265568/0985f69e-f9b3-11e6-9a0c-7fe8d656ace8.png)

Is this something that can be implemented? 

Thank you for all your hard work Kapiainen!

**Comment by Kapiainen** [comment]
Banners for Battle.net games should be in `\@Resources\Banners\Battle.net` and the names of the images should be the same as the name of the game folders (e.g. `Overwatch` should have an image called `Overwatch.jpg`, `Overwatch.png`, or something along those lines). Have you made sure that the banners conform to this? If Lauhdutin isn't downloading banners for Battle.net games, then check if `\@Resources\Cache\Battle.net store.html` exists and if it is empty. It should contain among other things links to the banners of games (you can open the file in a text editor and look for `alt="InsertGameNameHere"` where `InsertGameNameHere` could be e.g. `Hearthstone`). If that file looks like it is missing the links, then delete it, set Python path to `python` in the settings menu, and refresh the skin. The skin will get a new copy of the file and should download any missing banners. If there is an error, then it should hopefully show up in the terminal that pops up when you refresh the skin.

Banners for non-Steam and Windows shortcuts should be in `\@Resources\Banners\Steam shortcuts` and `\@Resources\Banners\Shortcuts\`, respectively, and the names of the images should match the names of the shortcuts (e.g. `The Witcher` should have an image called `The Witcher.jpg`, `The Witcher.png`, or something along those lines even though the game is shown as `Witcher, The` in the skin). Have you made sure that the banners conform to this?

**Comment by alszeliga** [comment]
Ah right, sorry, I had banners for my old Lauhdutin install! I moved them all to the new folder and followed your steps. Sorry for the oversight, and thanks for the detailed explanation! Love the skin.

**Comment by Kapiainen** [comment]
No problem. I'm glad to hear you got it sorted out.
