### ISSUE TITLE
Nothing showing up

### ISSUE THREAD

**Issue by roelofvkr** [Kapiainen/Lauhdutin#3]
Hey, I don't know if you're still updating this but okay..

I just downloaded the latest version and nothing is showing up, no error messages, nothing. I already looked through the code myself but i couldn't find anything. The rainmeter log says "Script: Lauhdutin.lua:391: attempt to index field '?' (a nil value)", i've already tried to print some of the variables used there and they seem to print the info just fine.

thanks,

**Comment by Smosse10** [comment]
I have the same error / log message.

**Comment by Kapiainen** [comment]
Odd. [Line 391](https://github.com/Kapiainen/Lauhdutin/blob/master/Lauhdutin/Lauhdutin.lua#L391) only contains the *end* keyword.

**Comment by RMAN0098** [comment]
oh shit i typo-ed sorry, that should say 291

**Comment by Kapiainen** [comment]
If the error is on line 291, then it seems like the following has the value nil:

```
tAppManifest[S_VDF_KEY_APP_STATE][S_VDF_KEY_USER_CONFIG]
```

Sounds like an issue with the contents of an AppManifest (.acf file containing info about an installed game). Could you add the following line somewhere below [line 287](https://github.com/Kapiainen/Lauhdutin/blob/master/Lauhdutin/Lauhdutin.lua#L287) but before line 291?

```
print(sAppID)
```

That should print out the Steam AppID of each game as they are being processed and the last one to get printed should be the AppManifest that is causing the error. Have a look at the contents of *\Steam\SteamApps\appmanifest_X.acf* (replace X with the last AppID in Rainmeter's log) with a text editor of some kind (e.g. Sublime Text, Notepad, Atom). The contents should have a structure similar to the following:

```
"AppState"
{
	"name"		"A game's title"
	(...)
	"UserConfig"
	{
		"name"		"A game's title"
	}
	(...)
}
```

This is a heavily simplified example. I replaced irrelevant lines with **(...)**. In your case it sounds like the *"AppState"* dictionary does not have an entry with the key *"name"*. During development I noticed that some AppManifests have an instance (or the only instance) of that entry in the *"UserConfig"* dictionary, which is what line 291 is trying to access in the case where line 289 fails to get the game's title.

**Comment by RMAN0098** [comment]
Hey, i looked at it and i think the problem is that you can remove steam games, but that won't delete the appmanifest_X.acf, it'll just make it empty. Maybe its a good idea to check if the file is empty when scanning it and skipping it (not including it) when it is

**Comment by Kapiainen** [comment]
Odd. I installed and uninstalled games repeatedly during development to see if the skin reacted appropriately and I never encountered a situation where a game's .acf file was not removed during the uninstall process. Did you just delete the game folder or did you uninstall the game via Steam (or Windows' Control Panel)?

**Comment by RMAN0098** [comment]
via steam.. it might have had some issues deinstalling i guess

**Comment by Kapiainen** [comment]
Forgot to ask, but did the skin start working once you removed the .acf file?

**Comment by RMAN0098** [comment]
yes it did

**Comment by Kapiainen** [comment]
Ok, good. I'll have to do some testing on my end to see what would be the best way to fix the bug.
