### ISSUE TITLE
Needs optimization

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#31]
It's an amazing skin but you should try to optimize it as much as possible,

https://youtu.be/gYwD8X5nXS8

Or is it a Rainmeter error?
As you can see every skin lags when scrolling, including the custom icons

**Comment by Kapiainen** [comment]
I'll have look and see if I can fix it. I try to keep my Rainmeter setup to a minimum (e.g. no visualizers) so I haven't encountered this while testing. I guess I'll have to install a visualizer and see if I can replicate the issue.

**Comment by GlowMLG** [comment]
When I finish moving the finger to scroll it keeps scrolling a little bit more. That might help. It's hard to see if you only scroll up once, but when you spam up and down it's noticeable

**Comment by Kapiainen** [comment]
A new alpha version is out and I think I've found a solution that works quite well.

**Comment by GlowMLG** [comment]
Oh let me see

**Comment by GlowMLG** [comment]
Wow works like a charm now!
thanks! Great job :)
