### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#33]
Real time search?
Like you don't have to press enter when you're searching, as soon as you type d everything with d should appear

**Comment by Kapiainen** [comment]
That was one of the things I looked into when I first started working on the fuzzy search feature. However, it looks like it is not possible at the moment with the [InputText plugin](https://docs.rainmeter.net/manual/plugins/inputtext/). InputText would have to be modified or a completely new plugin would have to be created.

**Comment by GlowMLG** [comment]
Okay no problem I'll keep helping with new ideas
