### ISSUE TITLE
Run a script when you click a game

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#34]
It might sound weird but it'd be really useful when you're using Rainmeter Auto Closer. Everytime you'd click a game, like GTA (which is fullscreen, so you dont have to have rainmeter open), rainmeter would close. And when you close GTA, rainmeter would start again. It's really helpful for shitty pcs or to get a little more power. My set-up is using 70MB. it's not much but it helps.

Or maybe you could even do another Rainmeter Auto Closer by yourself, but that's a lot of work

And you would be able to disable/enable all of them from settings, and then individually just like the hide game feature

what do you think?

https://www.reddit.com/r/Rainmeter/comments/5e3y7s/rainmeter_closer_while_gaming/

**Comment by Kapiainen** [comment]
Lauhdutin already has settings for executing Rainmeter bangs when you start and stop playing a game. You can use that to temporarily disable skins (e.g. visualizers) while playing a game.

**Comment by GlowMLG** [comment]
Oh wow i didn't see it.

Do you have any tutorial on how to use it?

**Comment by Kapiainen** [comment]
You can find the official Rainmeter documentation on bangs [here](https://docs.rainmeter.net/manual/bangs/). If you want to use multiple bangs, then you have to enclose each one in square brackets and quotations marks (single, `'`, or double, `"`) have to be replaced by backticks ``` ` ``` (e.g. ```[!Log `Message 1`][!Log `Message 2`] ```).

**Comment by GlowMLG** [comment]
Thanks!

**Comment by PointlessSheep** [comment]
Slightly unrelated but do you think there might be a way to disable rainmeter when my laptop is on battery? But thanks for the plugin otherwise!
