### ISSUE TITLE
Show all games, both installed and not

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#37]
Hello, I open a pull requests but I don't know how to do it and I think I open it wrongly, so better I open it here.

I try with adding this line to the 307 line of GUI.lua and when I put in the search "installed:all" it shows me both installed and not installed. I am not sure if it needs more parts to be modificated, but right now I think this way it works.

		elseif StartsWith(asPattern, 'a') then
			for i, game in ipairs(T_NOT_INSTALLED_GAMES) do
				table.insert(tResult, game)
			end
			for i, game in ipairs(T_ALL_GAMES) do
				table.insert(tResult, game)
			end

**Comment by Kapiainen** [comment]
This filter tag and a similar one for hidden games will be in version 2.7.0 as version 2.6.0 is in its beta phase, which entails a feature freeze.
