### ISSUE TITLE
How to add a new category for games.

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#41]
Hello again. I tried to create a new category for Origin and uPlay games, with functioning similar as Windows Shortcuts, to set up a filter to show only Origin or uPlay games. But I can't get it to work, I edited enums.py, GetGames.py, GUI.lua and created an "OriginShortcuts.py" but when I start again the skin it get stucks in "Initializing backend". The idea is to create folders separated to Origin and uPlay and get the shortcuts from there, to leave Windows Shortcuts for windows ordinary games.

I am not sure if I am overlooking some file or it's not possible to add new categories right now.

**Comment by Kapiainen** [comment]
Try setting the Python path setting to `python` to show the terminal. That should hopefully give you a bit more info on what is going wrong on the Python side of things.

**Comment by BanCrash** [comment]
If I do that without undo all the changes I made it only close right after opening. 
Well, I will research to see if I can get it to work. Thanks for the fast answer.

**Comment by Kapiainen** [comment]
Are you sure that your modifications do not contain any invalid Python code? Sounds like Python might be failing to parse your code. The backend scripts are set up to execute in a way that catches most runtime exceptions and shows the stack traceback rather than just close the terminal immediately.

**Comment by Kapiainen** [comment]
By the way, I'm wondering if it would be more appropriate to just modify `WindowsShortcuts.py` to support subfolders. So e.g. shortcuts placed in `\Lauhdutin\@Resources\Shortcuts\Origin` would show up as being from the Origin platform. My reasoning is that:
1) This would implement the ability to show a specific platform for an arbitrary number of possible values (Origin, Uplay, Itch.io, etc.). So no need to add a slightly modified copy of `WindowsShortcuts.py` for every platform.
2) This would maintain consistency in terms of what needs to be done by the user. Properly supported platforms  (e.g. Steam) have their games acquired in an automated fashion based upon one or more settings whereas Windows shortcuts (and corresponding banners) have to be manually added by the user, which would be the case here.

A new key-value pair could be added to the GameKeys enum and GAME_KEYS table on the Python and Lua parts of the skin, respectively. A new filter along the lines of `shortcuts:` followed by the subfolder name (e.g. `shortcuts:origin`) could be added.

What do you think?

**Comment by BanCrash** [comment]
Probably is that, I am not much versed on python to be honest. 

Sounds good, I think you are right, your way is much better than mine!

**Comment by Kapiainen** [comment]
I'll start working on that then.

**Comment by BanCrash** [comment]
Thanks you so much, I tried it but I can't make it to work.

**Comment by Kapiainen** [comment]
Support has been added for one level of subfolders and the `new-filter-tag` branch has also been merged into `next-version`, which is where the development of version 2.7.0 will continue. The `new-filter-tag` branch will be deleted as soon as any pending pull requests have been resolved.
