### ISSUE TITLE
Bang that closes rainmeter when you click and opens it when you close the program?

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#46]
I know I have to follow [this](https://docs.rainmeter.net/manual/bangs/) guide but I don't get how to install them in the skin nor how to exactly do this

I'm guessing I'd have to use !Quit, but how do you open it again once you close the program? It's from Rainmeter, so if it's closed there's no way you can open it from rainmeter... right?

Thanks

Edit: Maybe it could be done with !Hide, but would the skin still consume RAM&CPU Usage?

**Comment by Kapiainen** [comment]
If you want to reduce RAM and CPU usage, then your best bet is to toggle/disable skins. If you want to do that to multiple skins, then it might be more convenient to switch layouts.
