### ISSUE TITLE
Warcraft 3 and Frozen Throne path and executables

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#49]
I download Warcraft 3 and Frozen Throne expansion from battle.net, but before start I must say that those games can't be installed nor launched with battle.net client, only via web to download and normal shortcut to execute them. I see in the official forum that 2 years ago Blizzard said that they will implement the option to do that, but today that not happened yet.

Default path for both (expansion will be installed in the path of the Warcraft 3) is: C:\Program Files (x86)\Warcraft III\

Executables are: Warcraft III.exe for normal game, and Frozen Throne.exe for the expansion (both in the root folder, so C:\Program Files (x86)\Warcraft III\(game).exe ). However, when I launch the normal game or the expansion the executable that appears in the task manager is War3.exe, so I think that both executables are just shortcuts with .exe extension that sends a concrete command to War3.exe to execute one or other game.

I guess the better way is to add both like normal shortcuts, but just in case I'm wrong I let you here the information.

**Comment by Kapiainen** [comment]
Thanks for letting me know. The classic/legacy games can just as well be added as any other shortcut would as you suggested. I'll update the readme.
