### ISSUE TITLE
[idea] Mouse over on game banner

### ISSUE THREAD

**Issue by Ringeril** [Kapiainen/Lauhdutin#5]
I've been using for a while. But, I feel like it needs a little more interactivity.
Something like this:

![Idea](http://i.imgur.com/lWsK99Z.png)

**Comment by Kapiainen** [comment]
Finally found the motivation needed to work on this project and this feature will be in an upcoming update ([relevant branch](https://github.com/Kapiainen/Lauhdutin/tree/gui-improvements)).
