### ISSUE TITLE
About bangs 

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#50]
I'm trying to make a simple hide and show when a game is open but is there a way to ignore a game? I have a folder shortcut and I don't want to hide Rainmeter with that. Just because even if I close the folder window the stopping bang won't load

**Comment by Kapiainen** [comment]
It is not currently possible to do that. I can look into possibly implementing user defined exceptions for that on a game-by-game basis. For now you can use the skin's *Execute stopping bang* context menu option (right-click on the skin > *Custom skin actions* > *Execute stopping bang*).

**Comment by GlowMLG** [comment]
Thank you :)
