### ISSUE TITLE
About the bang exceptions you told me you might do

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#51]
So you told me you might make a bang exceptions system, but could you also do the opposite?

For example, you can't open overwatch directly. You have to open the battle.net client first, and then click on Play

Could you make it so you can add different executables apart from the widget ones?

Thanks

**Comment by Kapiainen** [comment]
I could add settings to set all games to execute/not execute bangs by default and then the user can disable/enable it for each game specifically.

Overwatch can definitely be launched directly:
A) Launch `\Overwatch\Overwatch.exe`, but then you have to manually log in with your Battle.net credentials.
B) Execute the `battlenet://Pro` command **while** the Battle.net client is running and you will be logged in automatically just like you would if you pressed *Play* in the Battle.net client. This is what Lauhdutin does, if you configured the skin's path setting for Battle.net games correctly. If you don't have the Battle.net client running, then the Battle.net client will just be opened.

I'm not sure I understand what your final question is referring to.

**Comment by GlowMLG** [comment]
I mean that if you could execute the bang If i opened, let's say, Doom, even if it wasn't from the widget and I opened it from the folder

**Comment by Kapiainen** [comment]
At the moment I cannot think of a good solution to make that happen automatically. Opening the folder via Lauhdutin would execute the *starting* bangs, but you would have to manually execute the *stopping* bangs to trigger it correctly every time. The current method that is used to automatically execute the *stopping* bangs is to monitor a single process (e.g. for Steam games it involves monitoring the process of Steam Overlay) until it stops running. There is no\* way of knowing which process the user started if (s)he were to manually start a program in a folder.

\* I can think of one solution, but it is a **very** poor solution that is prone to mistakes.
