### ISSUE TITLE
Skin doesn't display games

### ISSUE THREAD

**Issue by StriderStrifer** [Kapiainen/Lauhdutin#52]
Hello!

My skin has a No games to display message, although the previous version I used displayed all my games correctly.

Lauhdutin version 2.6.0

Rainmeter version 4.0.0

Python version 3.6.0

Windows 10, 64-bit

Python stack traceback:

Running on Python 3.6.0
Processing Windows shortcuts...
Processing Battle.net games...
Processing Steam games...
                Failed to process 'sharedconfig.vdf'
                Failed to process 'localconfig.vdf'
        Found library 'C:Program Files (x86)Steam'
        Found 0 games that are installed
Processing Steam shortcuts...
Generating master list of games...
Found 0 games...
Comparing new master list of games with old master list of games...
Downloading banners for 0 games from supported platforms...
Writing master list of 0 games to disk...
Initializing frontend...
Execution time: 0 minutes 0.23 seconds

I checked and I have both the sharedconfig.vdf and localconfig.vdf files in my Steam\userdata\SteamID folder. My Steam Library is on another disk, though it wasn't a problem before. I did a completely fresh instalation of the skin, following the instructions provided in the Readme.

**Comment by BanCrash** [comment]
Hello, In that log I see that the Steam path is set to 'C:Program Files (x86)Steam'.
Maybe the problem is that the correct path is 'C:**\**Program Files (x86)**\**Steam' ??

**Comment by StriderStrifer** [comment]
When I input it as 'C:\Program Files (x86)\Steam' in Settings it automatically gets turned into 'C:Program Files (x86)Steam' when I hit Enter.

**Comment by BanCrash** [comment]
Sorry, Now I See that the skin uses the / nor \.

Try with 'C:/Program Files (x86)/Steam'. Should work.

**Comment by StriderStrifer** [comment]
Tried and it's working. All my Steam games are here. Athough it is not finding my Battle.net games, but it's not that big of an issue.

Thanks a lot!

**Comment by BanCrash** [comment]
Glad to help. About Battle.net games, maybe the problem is the same?

**Comment by StriderStrifer** [comment]
I corrected the Battle.net path at the same time as the Steam one, but no dice. Maybe the issue might be that my game is installed in the 'D:/Program Files (x86)/Overwatch' folder, and not 'D:/Program Files (x86)/Battle.net' folder? Though I tried adding the 'D:/Program Files (x86)/Overwatch' folder, but it's still not finding anything.

**Comment by Kapiainen** [comment]
The path(s) for Battle.net games should point at the folder containing the folders of games. For example, I've installed all of my Battle.net games to `D:\Games\Blizzard\` (e.g. `D:\Games\Blizzard\Overwatch`) so I'm using `D:/Games/Blizzard` as the value of that setting. Try using `D:/Program Files (x86)` as the value of that setting.

**Comment by StriderStrifer** [comment]
Tried it and it works! I can't believe I haven't thought of that.

Thank you very much!
