### ISSUE TITLE
Skin cannot find games when user specifies different install folder for games.

### ISSUE THREAD

**Issue by Qrbaker** [Kapiainen/Lauhdutin#6]
Occurs when the Steam Application itself is installed in one location (i.e. Program Files) and the actual games (steamapps\common) are installed elsewhere, as can be specified in Steam settings.

Proposed fix: have user specify specifically the location of SteamApps\Common folder, not just the general Steam directory.

**Comment by spdyrel** [comment]
In "UserSettings" I added 

> Steam Library on other drive.
SteamLibraryPaths=[insert path here]

That worked initially for me but I think there's a max amount of games it holds because my games sometimes disappear. Might be something I'm doing wrong though but give that a try.
