### ISSUE TITLE
How to use this new feature?

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#60]
> Added support for toggling whether or not a game executes bangs

Cant see it in custom skin actions

**Comment by BanCrash** [comment]
You have to press the middle button (the wheel button) of the mouse in the banner of the game you want to toggle it, and the third icon allow you to enable or disable that feature.

Moreover you have two new options about that feature in the functionality part of the settings, "execute bangs by default" and "set all games to execute bangs".

**Comment by GlowMLG** [comment]
Oh that's a pretty nice feature thanks!
