### ISSUE TITLE
Last alpha's scrolling is more laggy

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#61]
Previous version:
https://www.youtube.com/watch?v=gYwD8X5nXS8&feature=youtu.be (see only the scrolling, the visualizer lag was fixed)

New version 2.7.0.3 (and .1)
https://youtu.be/gub3Qx4En-k (the scrolling lag is back and is way less smooth)

I posted this issue https://github.com/Kapiainen/Lauhdutin/issues/31 because it was laggy in a previous version. You fixed it and it worked perfectly, but looks like it's back. Also the scrolling itself feels less smooth. I'm doing the same movement, it gets stuck at the beginning and lags

**Comment by Kapiainen** [comment]
Good catch. Should be fixed in 2.7.0 alpha 4. Using a hover animation will still cause visualizers to lag, but I'm not sure if there is anything that can be done about that.

**Comment by GlowMLG** [comment]
Thanks! As the scrolling goes from game to game and isn't as precise as in a web, for instance, you could just the hover **image** that follows the mouse depending where it is. So there would only have to load it once. For example, you put your mouse over Doom, so you have that dark image with the play icon over it, but as you're scrolling and there's not even time to see the animation, just don't load it. Once you've stopped scrolling, start the animation onto whatever game the mouse is

I don't know if it's possible, just an idea. And sorry about my english, I'm not native

**Comment by Kapiainen** [comment]
The animations don't even play while scrolling at the moment, if the mouse cursor doesn't move. However, if you quickly hover the mouse cursor over multiple slots, then you'll see e.g. visualizers lagging out.

**Comment by Kapiainen** [comment]
I've been working on a major overhaul of the GUI and the issue with animations lagging out other skins should be reduced by quite a bit in the next alpha version, which I will probably be releasing in a day or two after some internal testing.

**Comment by GlowMLG** [comment]
Thanks! You're an amazing developer

**Comment by Kapiainen** [comment]
Thanks, I appreciate that. Alpha 5 is out.
