### ISSUE TITLE
BattleNet shortcut opens only Launcher

### ISSUE THREAD

**Issue by LinusHe** [Kapiainen/Lauhdutin#64]
When I click on a BattleNet shortcut (in my case Overwatch), only the BattleNet Launcher will be started.
Then I have to click on the Start Game Button to Start it.
Is it possible to fix that? And do you  also have this Bug?

**Comment by Kapiainen** [comment]
I have had this happen, but only when the Battle.net client is not already running. I usually just start the client and leave it running in a minimized state in the system tray. Try running the client and then launching a game via Lauhdutin. Does it still just open up the Battle.net client? An alternative way of running the game directly would be to create a shortcut to the game's executable, but then you will have to log in manually each time that you start the game instead of having the client automatically log you in.

**Comment by LinusHe** [comment]
Okay, when BattleNet is still running in Background, everything works.
There are now 2 other questions:
1) When the skin is started, it always takes a relatively long time until the game-shortcuts appear. For about 1-2 minutes, the "processing" message is there. Can this be optimized?
2) There are some Steam games that are not included. If I enter some games names in the search bar, they do not appear.
Examples are: Wolfenstein: The New Order, Dark Souls III, Battleblock Theater, Cities Skylines, Starbound, Farming Simulator 17 ...
What is the reason for this? It would be very unfortunate if only about 40% of my library would be contained.

Thanks for the quick reply so far.

**Comment by Kapiainen** [comment]
1. It should not take very long (unless you have a **massive** amount of games or really slow hard drives). Try setting the `Steam profile` setting to `Ignore`. If the processing time is reduced, then the long processing times might be related to your internet connection or the content delivery network that Steam uses. The Steam profile is used to figure out which games you have in your Steam account, but not necessarily installed at the moment, and for how long you have played the games. Depending on how you use Lauhdutin, it might not be necessary to have the setting enabled at all after the first time. 1-2 minutes is unusual unless you are using the skin for the first time and it is downloading banners for all of your games.

2. Are those games installed at the moment? If not, then they should be visible once you right-click on the skin, click on *Custom skin actions*, and then click on *Show not installed* (or just filter using `installed:false`). If you then want to search the list of not installed games, then you should use the `+` prefix (e.g. `+wolfenstein`).

**Comment by LinusHe** [comment]
1. The processing time is now much shorter. I noticed that it was because Steam, Origin, BattleNet & Windows downloaded updates, and therefore my Internet was quite slow.

2. The Games are Installed.
(see the screenshots)
![games](https://cloud.githubusercontent.com/assets/26716809/24672260/6f73aa24-1974-11e7-944b-83a58d1691e3.JPG)
![resultofsearchingdarksouls](https://cloud.githubusercontent.com/assets/26716809/24672257/6f6f6b30-1974-11e7-9e8b-0415d2c9fdd2.JPG)
![resultofsearchingterraria](https://cloud.githubusercontent.com/assets/26716809/24672259/6f735876-1974-11e7-83a2-1a36f87ca035.JPG)
![resultofsearchingwolfenstein](https://cloud.githubusercontent.com/assets/26716809/24672258/6f707d54-1974-11e7-96e7-cc7d032be831.JPG)

_I have pressed the Enter key after I searched (If you think I would not have done this ;) )_

**Comment by Kapiainen** [comment]
Could you try setting the Python path setting to `python` to show the terminal and reload the skin? A bunch of stuff, which might help diagnose the issue, should be printed out.

Another thing that you could try is to load the skin and open up `\Lauhdutin\@Resources\games.json` in a text editor. Try looking for one of the games that are not showing in the skin. If you can find them, then it would be great if you could post an entry for such a game. For example:

```
{
	"platform": 0,
	"path": "steam://rungameid/201810",
	"title": "Wolfenstein: The New Order",
	"banner": "Steam\\201810.jpg",
	"lastplayed": "1486663382",
	"tags": {
	  "0": "Backlog"
	},
	"hourstotal": 9.4,
	"ignoresbangs": false
}
```

**Comment by LinusHe** [comment]
Output:

```
Running on Python 3.6.1
Processing Windows shortcuts...
        Found shortcut 'Battlefield 1.lnk'
        Found shortcut 'Battlefield 4.lnk'
        Found shortcut 'STAR WARS Battlefront.lnk'
        Found shortcut 'Titanfall2.lnk'
Processing Battle.net games...
        Found game 'Hearthstone'
        Found game 'Heroes of the Storm'
        Found game 'Overwatch'
        Found game 'World of Warcraft'
        Found game 'Overwatch'
Processing Steam games...
                Failed to process 'sharedconfig.vdf'
        Attempting to access commmunity profile...
        Successfully parsed community profile...
        Found library 'C:/Program Files (x86)/Steam'
                Found game 'Starbound'
        Found library 'D:\Games'
                Found game 'Terraria'
                Found game 'Call of Duty: Black Ops II'
                Found game 'Call of Duty: Black Ops II - Multiplayer'
                Found game 'Castle Crashers'
                Found game 'Call of Duty: Black Ops II - Zombies'
                Found game 'Chivalry: Medieval Warfare'
                Found game 'Stanley Parable, The'
                Found game 'Euro Truck Simulator 2'
                Found game 'Worms Clan Wars'
                Found game 'BattleBlock Theater'
                Found game 'Assassin's Creed IV Black Flag'
                Found game 'Rocket League'
                Found game 'Cities: Skylines'
                Found game 'Grand Theft Auto V'
                Found game 'Tabletop Simulator'
                Found game 'Wolfenstein: The New Order German Edition'
                Found game 'Brawlhalla'
                Found game 'Call of Duty: Black Ops III'
                Found game 'Chaos Reborn'
                Found game 'Life Is Strange'
                Found game 'SteamVR Performance Test'
                        Account does not have 'SteamVR Performance Test'
                Found game 'AdVenture Capitalist'
                Found game 'Portal Knights'
                Found game 'DARK SOULS III'
                Found game 'Ultimate Chicken Horse'
                Found game 'Garry's Mod'
                Found game 'Moonlight'
                Found game 'GRID 2'
                Found game 'Farming Simulator 17'
                Found game 'Portal 2'
                Found game 'Counter-Strike: Global Offensive'
        Found 32 games that are installed
        Checking for games that are not installed...
        Found 23 games that are not installed
Processing Steam shortcuts...
Processing GOG Galaxy games...
Generating master list of games...
Found 63 games...
Comparing new master list of games with old master list of games...
Downloading banners for 55 games from supported platforms...
        Failed to download banner at some point for 'Starbound - Unstable'
        Failed to download banner at some point for 'Call of Duty: Black Ops III - Descent DLC Pack'
        Failed to download banner at some point for 'GTA SA German Mac'
Writing master list of 92 games to disk...
Initializing frontend...
Execution time: 0 minutes 1.57 seconds
```

There are all the games, but they arent shown in the rainmeter skin :/

```
  {
    "platform": 0,
    "path": "steam://rungameid/288570",
    "title": "Wolfenstein: The New Order German Edition",
    "banner": "Steam\\288570.jpg",
    "lastplayed": "1481381821",
    "hourslast2weeks": 0,
    "hourstotal": 2.3,
    "hidden": true,
    "ignoresbangs": false
  },
```

there are a few games, where "hidden" is true, but i want have them in my skin.. :)
The Question is: why are they hidden?
When I change "hidden" to "false" the games will be displayed.

Here are my settings:
![settings](https://cloud.githubusercontent.com/assets/26716809/24673909/12885a8e-197a-11e7-82e2-681300351b8d.JPG)
![settings2](https://cloud.githubusercontent.com/assets/26716809/24673908/1285878c-197a-11e7-83be-4159edb73d73.JPG)

**Comment by Kapiainen** [comment]
There's only one spot in the Python backend that can set a Steam game to be hidden and that would occur when finding a game locally, but not finding it in the Steam community profile. One possibility is that the community profile was not up-to-date (e.g. you just purchased a game, installed it, and the Steam community profile had not updated to show that you had the game). Another possibility is that at some point the skin was set to use another account, which does not have those games and set to be hidden. The flag would then be carried over the next time the skin was loaded (even if the Steam account had changed). I don't know how likely either of those scenarios are in your case. Maybe there is another scenario that I cannot think of at the moment.

**Comment by LinusHe** [comment]
> Another possibility is that at some point the skin was set to use another account, which does not have those games and set to be hidden.

That was it. Thank you very much!
(I've deleted the games.json, to re-initialize the games -> now they are complete. ;) )
