### ISSUE TITLE
Submenu not working as expected

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#68]
Hello, I am using the last beta, and when I tried to use any item of the submenu nothing happens.

In the rainmeter debuggin appears:

![image](https://cloud.githubusercontent.com/assets/11770760/25361851/c0c388b8-2950-11e7-8aaf-b4657b62a80f.png)

(Each error is for one different item of the submenu).

EDIT: I think I found the solution, it is just renaming _GetGames to Getgames. I will create a Pull request for if that the case, I tried right now and I think it works.

**Comment by Kapiainen** [comment]
Fixed in the upcoming version. Thanks for reporting it.
