### ISSUE TITLE
Load programs with bangs

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#75]
So I wanted to know if it's possible to load different executables when you open a game

For example, I always use haste when I play overwatch, but I don't need it when I'm not playing, since it consumes resources. 

is there a way to do this?

**Comment by Kapiainen** [comment]
Starting a program is as simple as modifying the starting bangs setting of the skin to include something like:

`["notepad"]`

or

`["C:/Windows/notepad.exe"]`

The former would work for programs that have been added to Windows' *PATH* system variable, but you can also just use the absolute path to an executable.

If you want to automatically close the program when you quit a game, then you can add something like the following to the stopping bangs setting:

`["taskkill" "/im" "notepad.exe"]`

If the game crashes, then that would also close the program, which might not be what you want to happen in that situation. So it might be best to just manually close the program when you are finished with the game.

That being said, it is not currently possible to execute specific bangs on a game-by-game basis. However, that does sound like a feature that could be added in the next version.

**Comment by GlowMLG** [comment]
Oh wow nice thanks a lot :)

**Comment by mk89pwnz** [comment]
Sorry for commenting on closed issue but this helped me a lot, any way to make start bang check if for example notepad.exe is not running and only then start it? Also anyway to force it run minimized?
