### ISSUE TITLE
Automatically set the settings skin as draggable, and set it back to the original position

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#76]
My skin is set so I can't drag it by mistake or whatever, and everytime I go to the settings skin by right clicking or whatever, I have to set it to draggable and back whan I'm done, since the skin is at the bottom right corner and it's cut when the skin changes

http://i.imgur.com/PdbfOI1.jpg

Thanks

**Comment by Kapiainen** [comment]
I can make the launcher and the settings into separate skins (i.e. `\Lauhdutin\Launcher\Main.ini` and `\Lauhdutin\Settings\Settings.ini`) in the next version. You should then be able to set e.g. the draggable setting separately for each skin.

**Comment by GlowMLG** [comment]
Thanks!!
