### ISSUE TITLE
Exception raised in the backend: Invalid control character at: line 294 column 7 (char 7901)

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#77]
So i finished my last setup yesterday and it was working perfectly, but after turning on the pc again it shows this error. First it didn't load, so I manually refershed it. Then it showed the message

http://i.imgur.com/9ZB86dr.jpg

*******

E: Rebuilding/refreshing doesn't work neither. I'm using the Beta 6. Do I just reinstall?

E2: So I've reinstalled as if I were updating it, and now it's stuck at *Processing*

Opened main.ini, the line 294 just says

> [FilterInput]
> Measure=Plugin
> Plugin=InputText
> X=0
> Y=50
> W=#ToolbarWidth#
> H=40
> SolidColor=#SlotBackgroundColor#
> FontColor=#SlotTextColor#
> FontFace=Arial //Line 294
> FontSize=20
> StringAlign=Center
> DefaultValue=
> FocusDismiss=1
> Command1=[!CommandMeasure "LauhdutinScript" "OnFinishedInputtingFilter('$UserInput$')"]
> OnDismissAction=[!CommandMeasure "LauhdutinScript" "OnDismissFilterInput()"]

Maybe it's a problem with inputtext.dll? Arial is installed. Mmmm changed Arial to Calibri and still nothing

Let me reinstall ranmeter then. Hmmm I've installed 4.1 and still doesn't work

*******

maybe it's from settings.ini?

It says 

> [SlotWidthStatus]
> Meter=String //Line 294
> MeterStyle=LayoutNumberStatusTemplate
> LeftMouseUpAction=[!CommandMeasure "SlotWidthInput" "ExecuteBatch 1"]

**Comment by BanCrash** [comment]
That sounds like a problem in games.json, could you share that line on that file??

**Comment by Kapiainen** [comment]
As @BanCrash mentioned, try modifying the Python path setting so that the terminal is visible. That should give more information about where in the Python scripts the error is occurring.

**Comment by GlowMLG** [comment]
Running on Python 3.5.3
Processing Windows shortcuts...
        Found shortcut 'besiege.lnk'
        Found shortcut 'Dark souls 1 I prepare to die edition.lnk'
        Found shortcut 'Dark souls 2 II.lnk'
        Found shortcut 'Dark souls 3 III.lnk'
        Found shortcut 'Disgaea 2.lnk'
        Found shortcut 'Emuladores.lnk'
        Found shortcut 'enter the gungeon.lnk'
        Found shortcut 'fallout 4.lnk'
        Found shortcut 'gta v.lnk'
        Found shortcut 'Life Is Strange.lnk'
        Found shortcut 'mass effect 2.lnk'
        Found shortcut 'Mass effect.lnk'
        Found shortcut 'Metal gear solid V 5 the phantom pain.lnk'
        Found shortcut 'ori and the blind forest.lnk'
        Found shortcut 'Overwatch.lnk'
        Found shortcut 'Portal 2.lnk'
        Found shortcut 'Rayman Legends.lnk'
        Found shortcut 'Rayman Origins.lnk'
        Found shortcut 'The Elder Scrolls V Skyrim Special Edition.lnk'
        Found shortcut 'The witcher 3 III.lnk'
        Found shortcut 'Tomb Raider.lnk'
        Found shortcut 'undertale.lnk'
Processing Battle.net games...
Processing Steam games...
                Failed to process 'sharedconfig.vdf'
                Failed to process 'localconfig.vdf'
        Found library 'M:/Mario/Programas/Steam'
                Found game 'Geometry Dash'
        Found library 'M:\Mario\Programas\SteamLibrary'
                Found game 'Maize'
                Found game 'DOOM'
                Found game 'Garry's Mod'
                Found game 'Borderlands 2'
        Found 5 games that are installed
Processing Steam shortcuts...
Processing GOG Galaxy games...
Generating master list of games...
Found 27 games...
Comparing new master list of games with old master list of games...
Traceback (most recent call last):
  File "M:\Mario\Documents\Rainmeter\Skins\Lauhdutin - copia\@Resources\Backend\GetGames.py", line 150, in <module>
    all_games_old = read_json(os.path.join(ResourcePath, "games.json"))
  File "M:\Mario\Documents\Rainmeter\Skins\Lauhdutin - copia\@Resources\Backend\GetGames.py", line 76, in read_json
    return json.load(f)
  File "C:\Users\Mario\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Mario\AppData\Local\Programs\Python\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Mario\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Mario\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 294 column 7 (char 7901)

**Comment by GlowMLG** [comment]
And in games.json

  {
    "lastplayed": 0,
    "ignoresbangs": true,
    "platform": 0,
    "hourstotal": 0.0,
    ", //here's an error and the Line 294
  : "steam://rungameid/8500",
    "notinstalled": true,
    "banner": "Steam\\8500.jpg",
    "title": "EVE Online"
  },

**Comment by GlowMLG** [comment]
Okay it's working now, I fixed the weird ",

thanks!!
