### ISSUE TITLE
Disable not Steam running?

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#79]
It's a nice feature but i find it annoying and maybe too colorful for what actually means nothing, since by clicking it automatically loads the client.

Can you make it so we can disable this option? Thanks!

**Comment by Kapiainen** [comment]
There is a setting for that: *Appearance* > *Platform running*. Just disable that setting.

**Comment by goktugacik** [comment]
It says steam is not running even it is running. Where is the appearance tab is located I couldn't find it
