### ISSUE TITLE
No Steam games found?

### ISSUE THREAD

**Issue by Nathipha** [Kapiainen/Lauhdutin#8]
Hi,

do you still support this skin?
If so: I can't get it to load any of my Steam games. :/
I set the user ID according to the "localconfig.vdf" file and the Steam folder is set to the path of Steam's exe (but without the "Steam.exe") but the only game it added automatically (I had to add a banner myself) was a non-Steam game that I added to my library a while ago. Apart from that it didn't find anything, the "Exceptions.inc" file is empty and there are no warnings, errors or debug messages in Rainmeter's logs when I reload your skin.

Rainmeter: Tested with both 3.3.2 final and 4.0 beta

Any suggestions what I could try to get it to work?
Could this possibly be an iusse with the locations? Rainmeter is installed on my system drive, Steam is installed on an extra HDD that also has a few games on it and there's another Steam library on a third HDD.

Edit:
Is there a way to have the sorting default to A-Z instead of "Last used"?

**Comment by pfmanderson** [comment]
I have the same issue.  Just says "No games to show Check readme"

steampath is set correctly, so is the userdataid.

I also have my games installed on more than one drive.

**Comment by mutex36** [comment]
Hey is there any progress on this issue?

**Comment by pfmanderson** [comment]
@mutex36 I messaged the author on reddit about this issue about 2 months ago, and he told me to download the vdf-update branch, which worked.  Now, that branch doesn't exist, but I see that his last commit was around 2 months ago, so I assumed he merged that branch into the master.

Are you still having the issue with a fresh download and install of the skin?

**Comment by Kapiainen** [comment]
I won't be providing support for versions other than the latest version. If anyone is experiencing this issue with a version of Lauhdutin older than the latest one, then update to the latest version. If there are still issues, then feel free to open a new issue.
