### ISSUE TITLE
Anything special with 3.0?

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#80]
Do you have anything special for the jump? Or wil you just keep going with 2.10?

Just wanted to know :)

Cheers!

**Comment by Kapiainen** [comment]
I usually keep [this issue](https://github.com/Kapiainen/Lauhdutin/issues/18) up-to-date with my current plans for upcoming versions. At this moment I don't have any plans for a complete rewrite nor for changes that would break backwards compatibility with e.g. `settings.json` or `games.json`. I don't think version 3.0.0 will be a thing in the near future and instead I'll just keep incrementing the minor and patch versions as necessary.
