### ISSUE TITLE
Double click option

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#81]
I sometimes click one of my games by mistake, resulting in lag until I'm able to close it. It'd be amazing to make it so they only open by clicking twice.   
What do you think? Thanks

**Comment by Kapiainen** [comment]
I'll think about it. Maybe implement a setting for it? We'll see.

If you want to have that behavior right now, then you can just change [line 195 in `\Lauhdutin\@Resources\Frontend\BuildSkin.py`](https://github.com/Kapiainen/Lauhdutin/blob/master/Lauhdutin/@Resources/Frontend/BuildSkin.py#L195) from this:

`"""LeftMouseUpAction=[!CommandMeasure LauhdutinScript "OnLeftClickSlot(%s)"]""" % nSlotNumber,`

to this:

`"""LeftMouseDoubleClickAction=[!CommandMeasure LauhdutinScript "OnLeftClickSlot(%s)"]""" % nSlotNumber,`

Remember to rebuild the skin afterwards for it to take effect.

**Comment by GlowMLG** [comment]
Thank you!!
