### ISSUE TITLE
Not So Much an Issue 

### ISSUE THREAD

**Issue by Dhop84** [Kapiainen/Lauhdutin#82]
I'm New to Rainmeter and  GitHub so forgive my stupidity but I'm trying to install but I cant find where it is that I have to put the path where my steam directory is, could you point me in the right direction please? also I don't no how to just write a comment to ask for help on here, for future reference so I don't have to open a issue, could you tell me how I do that also please?

**Comment by Kapiainen** [comment]
There is a Rainmeter config (`\Lauhdutin\Settings.ini`) that contains the skin's settings. Load that instead of `\Lauhdutin\Main.ini` and adjust things to your liking, save, and exit.

As far as I know GitHub doesn't offer a default thread to just post comments so you are forced to open an issue.
