### ISSUE TITLE
Can't find GOG Galaxy games

### ISSUE THREAD

**Issue by igriess** [Kapiainen/Lauhdutin#83]
## Short description of the issue

I am having a problem with Lauhdutin not finding any games from GOG Galaxy. I have the GOG Galaxy settings set to the correct folder in ProgramData on the C drive. I have all of the GOG games installed on a separate drive from a previous installation of Windows, so could that be the reason why it can't find a list of games in ProgramData?

## Lauhdutin version

2.7.0 

## Rainmeter version

4.0.0 r2746. This is the latest stable version of Rainmeter.

## Python version

Python 3.6, and I installed using the installer

## Windows version

Windows 10 Pro 64 bit

## Error messages

There are no error messages listed in Rainmeter's log

## Python stack traceback

```
Processing Steam shortcuts...
Processing GOG Galaxy games...
Generating master list of games...
Found 270 games...
Comparing new master list of games with old master list of games...
Downloading banners for 252 games from supported platforms...
        Failed to download banner at some point for 'Arma 2: Operation Arrowhead Beta (Obsolete)'
Writing master list of 274 games to disk...
Initializing frontend...
Execution time: 0 minutes 1.21 seconds
```
So it doesn't even seem to be finding any GOG Galaxy games.

**Comment by Kapiainen** [comment]
Just to make sure: do you have GOG Galaxy installed and did you install the games via it? I ask because if both `C:\ProgramData\GOG.com\Galaxy\storage\index.db` and `C:\ProgramData\GOG.com\Galaxy\storage\productdetails.db` existed, then the stack traceback that you posted should include the message `Connecting to index database...` after the second line. That message is not there because one or both of those files are missing and the Python script that handles GOG Galaxy games returned an empty list.

**Comment by igriess** [comment]
Yes. GOG Galaxy is installed and the games were installed through the program. I recently had to wipe my computer, though, and the games were left over from a previous installation of Windows. I tried reinstalling a game to test if that was the problem, but that did not help. I have also tried reinstalling GOG Galaxy and that did not help either. The index.db file exists but the productdetails.db does not. The four files I have in ProgramData are galaxy.db, index.db, jobs.db, and ownership.db

**Comment by Kapiainen** [comment]
I just checked to be sure and not only do all of my GOG Galaxy games show up as not installed in the skin but I am also missing my copy of `productdetails.db`. I did recently update GOG Galaxy to version 1.2, which I suspect is the reason for `productdetails.db` being missing (it may have just been renamed).  I'll see what needs to be done to fix this issue.

**Comment by Kapiainen** [comment]
[Version 2.7.1](https://github.com/Kapiainen/Lauhdutin/releases) should fix the issue. Let me know if you still have issues with getting GOG Galaxy games to show up.

**Comment by Archmeister94** [comment]
I'm also having this issue, I've got Lauhdutin 2.7.1 and GOG 1.2.32 (Win 10)
