### ISSUE TITLE
Invalid Steam UserDataID and/or Steam path error

### ISSUE THREAD

**Issue by AlphaX4** [Kapiainen/Lauhdutin#9]
I have properly changed everything needed in the UserSettings.inc and restarted rainmeter multiple times both in and out of administrator mode to no avail.

I have even tried completely exiting out of steam ( no more steam processes running in background) and rainmeter, starting steam back up then rainmeter and i still get the same issue.

I will be attaching screen shots of the logs rainmeter in debug mode produces upon starting it up, and the UserSettings.inc file

![e32c60b4dc14f64e3ad383b63a465afd](https://cloud.githubusercontent.com/assets/18093230/17826299/e2c28d40-6634-11e6-9fa7-df50f889cd36.png)
![8ef6a39ced48ea80d5a74cae2e5c88d3](https://cloud.githubusercontent.com/assets/18093230/17826412/368f6604-6636-11e6-8ff3-ad5377190a3a.png)

**Comment by Kapiainen** [comment]
UserDataID's value should only be the set of numbers at the end of your current value. So change the line containing UserDataID to:

`UserDataID=160045874`
