### ISSUE TITLE
Nonetype not iterable

### ISSUE THREAD

**Issue by atytel** [Kapiainen/Lauhdutin#90]
## Short description of the issue
unable to load any info about steam games

## Lauhdutin version
2.7.1

## Rainmeter version
4.1

## Python version
3.6.1

## Windows version
win 10

## Error messages
none

## Steps to reproduce the issue
I dont know

## Python stack traceback
![dddd](https://user-images.githubusercontent.com/26722492/27248353-4d4ba880-52d0-11e7-8b2f-c24c9d22a352.PNG)

**Comment by Kapiainen** [comment]
Have you set all of the necessary settings for Steam (path to the Steam installation folder and selected an account)? It looks like one or both of those settings haven't been given valid values. The values of those settings are used to figure out paths to certain files, but if those values are incorrect/missing then the Python scripts will fail to process them.
