### ISSUE TITLE
Blank banners

### ISSUE THREAD

**Issue by Tene21** [Kapiainen/Lauhdutin#93]
After starting up Rainmeter following a restart during a driver update, I noticed that all the banners were blank and that the skin no longer scrolled.
Here's what it currently looks like. 
![image](http://i.imgur.com/yvA9MsI.png)
All of the visible games are shortcuts, but if I remove the .lnks from the Shortcuts folder I can see that the same thing is happening to Steam and Blizzard games.
Nothing in my settings has changed, and after changing the python path from pythonw to python, nothing in the console seems to be out of place.
Is there some way I can fix this?

**Comment by Kapiainen** [comment]
Any errors in Rainmeter's log?

**Comment by Tene21** [comment]
Nope, no errors in the log.

**Comment by Kapiainen** [comment]
Have you tried reinstalling the skin or installing it under a different name? Any issues with other Rainmeter skins? Which component's drivers did you update?

**Comment by Tene21** [comment]
It was graphics drivers. A fresh install under a different name works, strangely enough. Is there anything I can do to keep hour tracking and tags for games transferred over?

**Comment by Tene21** [comment]
The new install started doing the same thing after a refresh

**Comment by Kapiainen** [comment]
I'm wondering if the updated graphics drivers are messing with Rainmeter as a whole or if there was an issue with the updating process. It seems unlikely in my opinion that only a specific skin would be affected by it. Are you using any other skins? Do they have any issues after the driver update? Do you have any other skins that make use of Rainmeter's ability to detect e.g. scrolling the mouse wheel? If you do not have another skin to test with, then you can paste the following into a new `.ini` file, load it, scroll the mouse wheel while the cursor is on it, and check the log for messages:

```
[Rainmeter]
Update=1000
AccurateText=1

[MeterImage]
Meter=Image
SolidColor=128,128,128,255
W=100
H=100
MouseScrollUpAction=[!Log "Scrolling the mouse wheel up!"]
MouseScrollDownAction=[!Log "Scrolling the mouse wheel down!"]
```

The stats and tags are stored in `\Skins\Lauhdutin\@Resources\games.json`, which you can just copy over to a new install.

**Comment by Tene21** [comment]
None of my other skins are acting up, none of the others use scrolling, and that skin is able to detect scrolling without any problems.

**Comment by Kapiainen** [comment]
If the highlighting still works, like it seems to be doing based on the screenshot in your first post, then it doesn't seem to be an issue with the skin's Lua script either. Does the toolbar still work (searching, sorting, settings button)?

To be honest, I'm not sure what else to try at the moment short of the classic measure of restarting the computer. I really need to get some sleep as well, which isn't helping when trying to diagnose the issue. I'll have to think about this some more in the morning. I'll probably be back in about 9-10 hours from now.

**Comment by Tene21** [comment]
The toolbar still shows up and all the elements are clickable, but I can't verify if search and sort work because I can't see what the banners are. The settings still works, though. In all honesty restarting should have been my first port of call but I keep putting it off, so I'll do that now and see if it makes a difference.

**Comment by Tene21** [comment]
Restarting didn't do anything but I've noticed that I was wrong in my initial statement. Scrolling *does* still work, so it's just likely just a problem with the images being displayed.

**Comment by Kapiainen** [comment]
Okay, so it seems like it is "just" the banners. Did the banners show up like they should the first time that you loaded the newly installed skin? Did you do anything (e.g. edit or copy over files) between the first time that you loaded the skin and when you refreshed the skin?

Could you check whether the banners themselves are fine (`\Skins\Lauhdutin\@Resources\Banners`)? If the paths to the banners were incorrect for some reason (e.g. missing banners) could cause the banners to not be visible in the skin, but that would result in error messages, which you said there weren't, in Rainmeter's log. However, if the banners are corrupted, then the paths would still be valid and I'm not sure how Rainmeter handles corrupted images.

**Comment by Tene21** [comment]
The banners showed up on the first time but disappeared after a refresh of the skin. I didn't copy anything over, I just set the paths so that the skin would load my libraries properly. The banners themselves are all fine, I can open and view them in any viewer or editor and there doesn't seem to be anything wrong with them.

**Comment by Tene21** [comment]
I loaded the skin today after leaving it unloaded overnight and suddenly the banners are loading again. I have no idea what's changed since then, but it works now.

**Comment by Kapiainen** [comment]
That is odd. I'll leave this issue open for the time being in case the situation changes.
